SignalEasel: afsk_test.cpp File Reference
afsk_test.cpp File Reference
#include "gtest/gtest.h"
#include <string>
#include <SignalEasel/afsk.hpp>
Functions
TEST (Afsk, DecodeWithSignalSkew)
Pre-prepared WAV file with 20 samples added to the start of the file.
TEST (Afsk, EncodeDecodeBasicStringToWav)
Encodes a string into an AFSK1200 signal/WAV file and then decodes it.
TEST (Afsk, WhiteNoise)
Function Documentation
TEST() [1/3]
TEST (Afsk , EncodeDecodeBasicStringToWav)
Encodes a string into an AFSK1200 signal/WAV file and then decodes it.
References signal_easel::DataModulator::addString(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::afsk::Demodulator::lookForString(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::afsk::Demodulator::SUCCESS, and signal_easel::Modulator::writeToFile().
TEST() [2/3]
TEST (Afsk , DecodeWithSignalSkew)
Pre-prepared WAV file with 20 samples added to the start of the file.
20 samples is enough to throw the signal off by 1/2 of a bit. This should test the ability of the demodulator to sync to the signal.
References signal_easel::Demodulator::loadAudioFromFile(), signal_easel::afsk::Demodulator::lookForString(), signal_easel::afsk::Demodulator::processAudioBuffer(), and signal_easel::afsk::Demodulator::SUCCESS.
TEST() [3/3]
TEST (Afsk , WhiteNoise)
References signal_easel::Demodulator::loadAudioFromFile(), signal_easel::afsk::Demodulator::lookForString(), signal_easel::afsk::Demodulator::processAudioBuffer(), and signal_easel::afsk::Demodulator::SUCCESS.