SignalEasel: aprs_test.cpp File Reference
aprs_test.cpp File Reference
#include "gtest/gtest.h"
#include <SignalEasel/aprs.hpp>
#include <fstream>
Functions
TEST (Aprs, DecodeReal)
TEST (Aprs, EncodeAndDecodeExperimentalPacket)
TEST (Aprs, EncodeAndDecodeMessagePacket)
TEST (Aprs, EncodeAndDecodePositionPacket)
TEST (Aprs, EncodeAndDecodeTelemetryBitSense)
TEST (Aprs, EncodeAndDecodeTelemetryCoefficients)
TEST (Aprs, EncodeAndDecodeTelemetryDataReport)
TEST (Aprs, EncodeAndDecodeTelemetryParameterName)
TEST (Aprs, EncodeAndDecodeTelemetryParameterUnitOrLabel)
Function Documentation
TEST() [1/9]
TEST (Aprs , EncodeAndDecodeMessagePacket)
References signal_easel::aprs::MessagePacket::addressee, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Packet::MESSAGE, signal_easel::aprs::MessagePacket::message, signal_easel::aprs::MessagePacket::message_id, signal_easel::aprs::Demodulator::parseMessagePacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, and signal_easel::Modulator::writeToFile().
TEST() [2/9]
TEST (Aprs , EncodeAndDecodePositionPacket)
References signal_easel::aprs::PositionPacket::altitude, signal_easel::aprs::PositionPacket::course, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::aprs::PositionPacket::latitude, signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::PositionPacket::longitude, signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parsePositionPacket(), signal_easel::aprs::Packet::POSITION, signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, signal_easel::aprs::PositionPacket::speed, signal_easel::aprs::PositionPacket::time_code, and signal_easel::Modulator::writeToFile().
TEST() [3/9]
TEST (Aprs , EncodeAndDecodeExperimentalPacket)
References signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Packet::EXPERIMENTAL, signal_easel::aprs::ExperimentalPacket::getStringData(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::ExperimentalPacket::packet_type_char, signal_easel::aprs::Demodulator::parseExperimentalPacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::ExperimentalPacket::setStringData(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, and signal_easel::Modulator::writeToFile().
TEST() [4/9]
TEST (Aprs , DecodeReal)
References signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::printFrame(), and signal_easel::afsk::Demodulator::processAudioBuffer().
TEST() [5/9]
TEST (Aprs , EncodeAndDecodeTelemetryDataReport)
References signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parseTelemetryPacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, signal_easel::aprs::TelemetryPacket::telemetry_data, signal_easel::aprs::Packet::TELEMETRY_DATA_REPORT, signal_easel::aprs::TelemetryPacket::telemetry_type, and signal_easel::Modulator::writeToFile().
TEST() [6/9]
TEST (Aprs , EncodeAndDecodeTelemetryBitSense)
References signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parseTelemetryPacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, signal_easel::aprs::Packet::TELEMETRY_BIT_SENSE_PROJ_NAME, signal_easel::aprs::TelemetryPacket::telemetry_data, signal_easel::aprs::TelemetryPacket::telemetry_type, and signal_easel::Modulator::writeToFile().
TEST() [7/9]
TEST (Aprs , EncodeAndDecodeTelemetryParameterName)
References signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parseTelemetryPacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, signal_easel::aprs::TelemetryPacket::telemetry_data, signal_easel::aprs::Packet::TELEMETRY_PARAMETER_NAME, signal_easel::aprs::TelemetryPacket::telemetry_type, and signal_easel::Modulator::writeToFile().
TEST() [8/9]
TEST (Aprs , EncodeAndDecodeTelemetryParameterUnitOrLabel)
References signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parseTelemetryPacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, signal_easel::aprs::TelemetryPacket::telemetry_data, signal_easel::aprs::Packet::TELEMETRY_PARAMETER_UNIT, signal_easel::aprs::TelemetryPacket::telemetry_type, and signal_easel::Modulator::writeToFile().
TEST() [9/9]
TEST (Aprs , EncodeAndDecodeTelemetryCoefficients)
References signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Modulator::encode(), signal_easel::aprs::Demodulator::getType(), signal_easel::Demodulator::loadAudioFromFile(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parseTelemetryPacket(), signal_easel::afsk::Demodulator::processAudioBuffer(), signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, signal_easel::aprs::Packet::TELEMETRY_COEFFICIENT, signal_easel::aprs::TelemetryPacket::telemetry_data, signal_easel::aprs::TelemetryPacket::telemetry_type, and signal_easel::Modulator::writeToFile().