SignalEasel: aprs_telemetry_data_test.cpp File Reference
aprs_telemetry_data_test.cpp File Reference
#include "gtest/gtest.h"
#include <SignalEasel/aprs/telemetry_data.hpp>
Functions
TEST (aprs_telemetry_data, getAnalogParamater)
TEST (aprs_telemetry_data, getDigitalParameter)
TEST (aprs_telemetry_data, setComment)
TEST (aprs_telemetry_data, setProjectTitle)
TEST (aprs_telemetry_data, setSequenceNumber)
Detailed Description
=*========SignalEasel========*= A friendly library for signal modulation and demodulation. https://signaleasel.joshuajer.red/ https://github.com/joshua-jerred/SignalEasel =*=======================*=
Date
2024-08-17 =*=======================*=
Copyright
2024 Joshua Jerred
License: GNU GPLv3
Function Documentation
TEST() [1/5]
TEST (aprs_telemetry_data , getAnalogParamater)
References signal_easel::aprs::telemetry::TelemetryData::getAnalog().
TEST() [2/5]
TEST (aprs_telemetry_data , getDigitalParameter)
References signal_easel::aprs::telemetry::TelemetryData::getDigital().
TEST() [3/5]
TEST (aprs_telemetry_data , setSequenceNumber)
References signal_easel::aprs::telemetry::TelemetryData::getSequenceNumber(), signal_easel::aprs::telemetry::TelemetryData::getSequenceNumberString(), and signal_easel::aprs::telemetry::TelemetryData::setSequenceNumber().
TEST() [4/5]
TEST (aprs_telemetry_data , setComment)
References signal_easel::aprs::telemetry::TelemetryData::getComment(), and signal_easel::aprs::telemetry::TelemetryData::setComment().
TEST() [5/5]
TEST (aprs_telemetry_data , setProjectTitle)
References signal_easel::aprs::telemetry::TelemetryData::getProjectTitle(), and signal_easel::aprs::telemetry::TelemetryData::setProjectTitle().