SignalEasel: aprs_receiver_test.cpp File Reference
aprs_receiver_test.cpp File Reference
Integration tests for signal_easel::aprs::Receiver.
#include "gtest/gtest.h"
#include <SignalEasel/aprs.hpp>
#include <SignalEasel/ax25.hpp>
#include <wav_gen.hpp>
#include <memory>
#include <vector>
Classes
class signal_easel::aprs::FakePulseAudioReader
Fake PulseAudioReader that reads from a WAV file in chunks.
class signal_easel::aprs::TestableAprsReceiver
Testable version of aprs::Receiver that injects a fake pulse audio reader, exercising the full aprs::Receiver decode path.
Namespaces
namespace signal_easel
namespace signal_easel::aprs
Functions
TEST (AprsReceiver, DecodeMultipleAprsPacketsChunked)
Test that the receiver decodes multiple APRS packets from multi_packet_aprs.wav. All packets should be experimental packets with source KD9GDC-1, destination KD9GDC-11, type char 'b', and data "0000000acmd/dat/cae/".
TEST (AprsReceiver, DecodeRealAprsPacketChunked)
Test that the receiver properly decodes a real APRS packet from aprs_real.wav using the full aprs::Receiver pipeline.
Detailed Description
Integration tests for signal_easel::aprs::Receiver.
The aprs receiver implementation is known to be hot trash rn, however the decoder seems to work well. Basically, wav files good, pulse/live audio bad (10% success rate with decoding real packets)
How these tests differ from the non-pulse tests in aprs_test.cpp
The tests in aprs_test.cpp use aprs::Modulator and aprs::Demodulator directly: encode a packet to a WAV file, load the entire file into the demodulator at once with loadAudioFromFile(), call processAudioBuffer() once, then assert on the result. There is no signal-detection layer, no chunking, no SNR gating.
Because aprs::Receiver owns its own PulseAudioReader, a TestableAprsReceiver subclass is used here. It overrides process() to feed fake chunked data from a WAV file instead of a live audio device, while the inherited detectSignal() and decode() path runs unmodified.
Build and run
Must run from the build directory to find the test WAV files
cmake -S . -B build cmake –build build –target signal_easel_unit_tests cd build/tests && ./signal_easel_unit_tests –gtest_filter="AprsReceiver*"
Function Documentation
TEST() [1/2]
TEST (AprsReceiver , DecodeRealAprsPacketChunked)
Test that the receiver properly decodes a real APRS packet from aprs_real.wav using the full aprs::Receiver pipeline.
References signal_easel::aprs::Receiver::getStats(), signal_easel::aprs::TestableAprsReceiver::process(), and signal_easel::aprs::Receiver::Stats::total_message_packets.
TEST() [2/2]
TEST (AprsReceiver , DecodeMultipleAprsPacketsChunked)
Test that the receiver decodes multiple APRS packets from multi_packet_aprs.wav. All packets should be experimental packets with source KD9GDC-1, destination KD9GDC-11, type char 'b', and data "0000000acmd/dat/cae/".
References signal_easel::aprs::Receiver::getAprsExperimental(), signal_easel::aprs::Receiver::getStats(), signal_easel::aprs::ExperimentalPacket::getStringData(), signal_easel::aprs::ExperimentalPacket::packet_type_char, signal_easel::aprs::TestableAprsReceiver::process(), signal_easel::aprs::Packet::source_address, and signal_easel::aprs::Packet::source_ssid.