SignalEasel: aprs_telemetry_parameter_test.cpp File Reference
aprs_telemetry_parameter_test.cpp File Reference
#include "gtest/gtest.h"
#include <SignalEasel/aprs/telemetry_parameter.hpp>
Functions
TEST (aprs_telemetry_parameters_test, AnalogParameter_getCalculatedValue)
TEST (aprs_telemetry_parameters_test, AnalogParameter_getCoefficient_default)
TEST (aprs_telemetry_parameters_test, AnalogParameter_getRawValue)
TEST (aprs_telemetry_parameters_test, AnalogParameter_getScaledValue_default)
TEST (aprs_telemetry_parameters_test, AnalogParameter_setCoefficient)
TEST (aprs_telemetry_parameters_test, AnalogParameter_setName)
TEST (aprs_telemetry_parameters_test, DigitalParameter_setName)
Function Documentation
TEST() [1/7]
TEST (aprs_telemetry_parameters_test , AnalogParameter_setName)
References signal_easel::aprs::telemetry::Parameter::getId(), signal_easel::aprs::telemetry::Parameter::getName(), signal_easel::aprs::telemetry::Parameter::getType(), and signal_easel::aprs::telemetry::Parameter::setName().
TEST() [2/7]
TEST (aprs_telemetry_parameters_test , DigitalParameter_setName)
References signal_easel::aprs::telemetry::Parameter::getId(), signal_easel::aprs::telemetry::Parameter::getName(), signal_easel::aprs::telemetry::Parameter::getType(), and signal_easel::aprs::telemetry::Parameter::setName().
TEST() [3/7]
TEST (aprs_telemetry_parameters_test , AnalogParameter_getCoefficient_default)
References signal_easel::aprs::telemetry::AnalogParameter::getCoefficientA(), signal_easel::aprs::telemetry::AnalogParameter::getCoefficientB(), and signal_easel::aprs::telemetry::AnalogParameter::getCoefficientC().
TEST() [4/7]
TEST (aprs_telemetry_parameters_test , AnalogParameter_setCoefficient)
References signal_easel::aprs::telemetry::AnalogParameter::getCoefficientA(), and signal_easel::aprs::telemetry::AnalogParameter::setCoefficientA().
TEST() [5/7]
TEST (aprs_telemetry_parameters_test , AnalogParameter_getRawValue)
References signal_easel::aprs::telemetry::AnalogParameter::getCalculatedValue(), signal_easel::aprs::telemetry::AnalogParameter::getValue(), and signal_easel::aprs::telemetry::AnalogParameter::setRawValue().
TEST() [6/7]
TEST (aprs_telemetry_parameters_test , AnalogParameter_getScaledValue_default)
References signal_easel::aprs::telemetry::AnalogParameter::getCalculatedValue(), and signal_easel::aprs::telemetry::AnalogParameter::setRawValue().
TEST() [7/7]
TEST (aprs_telemetry_parameters_test , AnalogParameter_getCalculatedValue)
References signal_easel::aprs::telemetry::AnalogParameter::getCalculatedValue(), signal_easel::aprs::telemetry::AnalogParameter::setCoefficients(), signal_easel::aprs::telemetry::AnalogParameter::setRawValue(), and test().