SignalEasel: ax25_address_test.cpp File Reference
ax25_address_test.cpp File Reference
#include "gtest/gtest.h"
#include <SignalEasel/ax25.hpp>
#include <SignalEasel/exception.hpp>
Functions
TEST (Ax25_Address, arrayConstructor_decodeAddress)
TEST (Ax25_Address, basicConstructor)
TEST (Ax25_Address, checksAddressCharacters)
TEST (Ax25_Address, encodeAddress)
TEST (Ax25_Address, flag_bits_decode)
TEST (Ax25_Address, padsWithSpaces)
Function Documentation
TEST() [1/6]
TEST (Ax25_Address , basicConstructor)
References signal_easel::ax25::Address::getAddressString(), signal_easel::ax25::Address::getSsid(), and signal_easel::ax25::Address::isValid().
TEST() [2/6]
TEST (Ax25_Address , arrayConstructor_decodeAddress)
References signal_easel::ax25::Address::getAddressString(), and signal_easel::ax25::Address::getSsid().
TEST() [3/6]
TEST (Ax25_Address , encodeAddress)
References signal_easel::ax25::Address::encodeAddress().
TEST() [4/6]
TEST (Ax25_Address , checksAddressCharacters)
TEST() [5/6]
TEST (Ax25_Address , padsWithSpaces)
References signal_easel::ax25::Address::encodeAddress(), and signal_easel::ax25::Address::getAddressString().
TEST() [6/6]
TEST (Ax25_Address , flag_bits_decode)
References signal_easel::ax25::Address::isCommandOrResponse(), signal_easel::ax25::Address::isLastAddress(), signal_easel::ax25::Address::isReservedBit1Set(), and signal_easel::ax25::Address::isReservedBit2Set().