Signal Easel: ax25_frame_test.cpp File Reference
ax25_frame_test.cpp File Reference
#include "gtest/gtest.h"
#include <SignalEasel/ax25.hpp>
Functions
TEST (Ax25_Frame, basicFrame)
Function Documentation
TEST()
TEST (Ax25_Frame , basicFrame)
References signal_easel::ax25::Address::assertIsValid(), signal_easel::ax25::Frame::isFrameValid(), signal_easel::ax25::Frame::setDestinationAddress(), and signal_easel::ax25::Frame::setSourceAddress().