SignalEasel: signal_easel::psk::Modulator Class Reference
signal_easel::psk::Modulator Class Reference
PSK Modulator.
#include <psk.hpp>
Public Member Functions
Modulator (psk::Settings settings=psk::Settings())
Constructor for the PSK Modulator.
~Modulator ()=default
void clearBuffer ()
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
void encodeString (const std::string &input)
void writeToFile (const std::string &filename)
Write the audio to a file.
void writeToPulseAudio ()
Write the audio to the default PulseAudio output device.
Protected Member Functions
void addAudioSample (int16_t sample)
Add a PCM sample to the audio buffer.
void addAudioSampleDouble (double sample)
Add a PCM sample to the audio buffer.
void addSilence (uint32_t duration_in_samples)
Add silence to the audio buffer.
void addSineWave (uint16_t frequency, uint16_t num_samples)
Add a sine wave to the audio buffer.
Protected Attributes
std::vector< int16_t > audio_buffer_ = {}
Private Member Functions
void addMorseCode (const std::string &input_string)
Add morse code to the output audio.
void addPostamble ()
void addPreamble ()
void addSymbol (double shift, int filter_end)
void addVaricode (const char c)
void encodeBpsk ()
void encodeQpsk ()
Private Attributes
double angle_delta_ = 0.0f
BitStream bit_stream_ {}
double carrier_wave_angle_ = 0.0f
int last_symbol_end_filtered_ = 1
uint32_t samples_per_symbol_ = 0
psk::Settings settings_
The settings for the modulator.
double sine_wave_phase_ = 0.0
Used with addSineWave to keep a continuous phase between calls.
Detailed Description
PSK Modulator.
Constructor & Destructor Documentation
Modulator()
signal_easel::psk::Modulator::Modulator (psk::Settings settings = psk::Settings()) inline
Constructor for the PSK Modulator.
Parameters
settings The settings for the modulator
~Modulator()
signal_easel::psk::Modulator::~Modulator () virtual default
Reimplemented from signal_easel::Modulator.
Member Function Documentation
encodeString()
void signal_easel::psk::Modulator::encodeString (const std::string & input)
References signal_easel::BitStream::addBits(), addPostamble(), addPreamble(), addVaricode(), angle_delta_, signal_easel::AUDIO_SAMPLE_RATE, bit_stream_, signal_easel::psk::Settings::BPSK, signal_easel::psk::Settings::carrier_frequency, carrier_wave_angle_, signal_easel::BitStream::clear(), encodeBpsk(), encodeQpsk(), last_symbol_end_filtered_, signal_easel::psk::Settings::mode, signal_easel::BitStream::pushBufferToBitStream(), samples_per_symbol_, settings_, and signal_easel::psk::Settings::symbol_rate.
Referenced by TEST().
addVaricode()
void signal_easel::psk::Modulator::addVaricode (const char c) private
References signal_easel::BitStream::addBits(), signal_easel::psk::AsciiToVaricodeArray, and bit_stream_.
Referenced by encodeString().
addPreamble()
void signal_easel::psk::Modulator::addPreamble () private
References signal_easel::BitStream::addZeroBit(), bit_stream_, signal_easel::psk::Settings::preamble_length, and settings_.
Referenced by encodeString().
addPostamble()
void signal_easel::psk::Modulator::addPostamble () private
References signal_easel::BitStream::addOneBit(), signal_easel::BitStream::addZeroBit(), bit_stream_, signal_easel::psk::Settings::fldigi_mode, signal_easel::BitStream::getBitStreamLength(), signal_easel::psk::Settings::mode, signal_easel::psk::Settings::postamble_length, signal_easel::psk::Settings::QPSK, and settings_.
Referenced by encodeString().
addSymbol()
void signal_easel::psk::Modulator::addSymbol (double shift, int filter_end) private
encodeBpsk()
void signal_easel::psk::Modulator::encodeBpsk () private
References signal_easel::psk::PskWaveShaper::addSymbol(), signal_easel::Settings::amplitude, signal_easel::Modulator::audio_buffer_, bit_stream_, signal_easel::psk::Settings::carrier_frequency, signal_easel::psk::ONE_EIGHTY, signal_easel::BitStream::peakNextBit(), signal_easel::BitStream::popNextBit(), settings_, signal_easel::psk::Settings::symbol_rate, and signal_easel::psk::ZERO.
Referenced by encodeString().
encodeQpsk()
void signal_easel::psk::Modulator::encodeQpsk () private
References signal_easel::psk::PskWaveShaper::addSymbol(), signal_easel::Settings::amplitude, signal_easel::Modulator::audio_buffer_, bit_stream_, signal_easel::psk::Settings::carrier_frequency, signal_easel::psk::getShiftedConvolutionalCodePhase(), signal_easel::BitStream::popNextBit(), settings_, signal_easel::psk::Settings::symbol_rate, and signal_easel::psk::ZERO.
Referenced by encodeString().
clearBuffer()
void signal_easel::Modulator::clearBuffer () inherited
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Settings::NONE, signal_easel::Modulator::settings_, and signal_easel::Modulator::sine_wave_phase_.
Referenced by signal_easel::Modulator::Modulator().
writeToFile()
void signal_easel::Modulator::writeToFile (const std::string & filename) inherited
Write the audio to a file.
Parameters
filename The name/path of the file to write to
Exceptions
MWAVException Throws an exception if the file cannot be opened or if there is no data to write
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Settings::AFTER, signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::FILE_OPEN_ERROR, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Exception::NO_DATA_TO_WRITE, signal_easel::Settings::NONE, and signal_easel::Modulator::settings_.
Referenced by TEST().
writeToPulseAudio()
void signal_easel::Modulator::writeToPulseAudio () inherited
Write the audio to the default PulseAudio output device.
References signal_easel::Modulator::audio_buffer_, signal_easel::PULSE_AUDIO_APP_NAME, signal_easel::Exception::PULSE_AUDIO_DISABLED, signal_easel::PULSE_AUDIO_SAMPLE_SPEC, signal_easel::Exception::PULSE_DRAIN_ERROR, signal_easel::Exception::PULSE_OPEN_ERROR, and signal_easel::Exception::PULSE_WRITE_ERROR.
Referenced by main().
addAudioSample()
void signal_easel::Modulator::addAudioSample (int16_t sample) inline protected inherited
Add a PCM sample to the audio buffer.
Parameters
sample The PCM sample to add
References signal_easel::Modulator::audio_buffer_.
Referenced by signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), and signal_easel::afsk::Modulator::encodeBytes().
addAudioSampleDouble()
void signal_easel::Modulator::addAudioSampleDouble (double sample) inline protected inherited
Add a PCM sample to the audio buffer.
Parameters
sample The PCM sample to add - -1.0 to 1.0
References signal_easel::Modulator::audio_buffer_.
addSilence()
void signal_easel::Modulator::addSilence (uint32_t duration_in_samples) inline protected inherited
Add silence to the audio buffer.
Parameters
duration_in_samples
References signal_easel::Modulator::addAudioSample().
Referenced by signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
addSineWave()
void signal_easel::Modulator::addSineWave (uint16_t frequency, uint16_t num_samples) protected inherited
Add a sine wave to the audio buffer.
Parameters
frequency The frequency of the sine wave in Hz
num_samples The number of samples to add
References signal_easel::Modulator::addAudioSample(), signal_easel::Settings::amplitude, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::MAX_SAMPLE_VALUE, signal_easel::Modulator::settings_, signal_easel::Modulator::sine_wave_phase_, and signal_easel::TWO_PI_VAL.
Referenced by signal_easel::Modulator::addMorseCode(), signal_easel::sstv::Modulator::pulse(), and signal_easel::sstv::Modulator::writeBuffer().
addMorseCode()
void signal_easel::Modulator::addMorseCode (const std::string & input_string) private inherited
Add morse code to the output audio.
Parameters
input_string the string to convert to morse code
References signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), signal_easel::DASH_LENGTH, signal_easel::DOT_LENGTH, signal_easel::Exception::EMPTY_INPUT_STRING, signal_easel::Exception::INVALID_MORSE_CHAR, signal_easel::LETTER_SPACE_LENGTH, signal_easel::MORSE_CODE_MAP, signal_easel::MORSE_TONE_FREQUENCY, and signal_easel::TIME_BETWEEN_SYMBOLS.
Referenced by signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
Member Data Documentation
settings_
psk::Settings signal_easel::psk::Modulator::settings_ private
The settings for the modulator.
Referenced by addPostamble(), addPreamble(), encodeBpsk(), encodeQpsk(), and encodeString().
bit_stream_
BitStream signal_easel::psk::Modulator::bit_stream_ {} private
Referenced by addPostamble(), addPreamble(), addVaricode(), encodeBpsk(), encodeQpsk(), and encodeString().
carrier_wave_angle_
double signal_easel::psk::Modulator::carrier_wave_angle_ = 0.0f private
Referenced by encodeString().
last_symbol_end_filtered_
int signal_easel::psk::Modulator::last_symbol_end_filtered_ = 1 private
Referenced by encodeString().
angle_delta_
double signal_easel::psk::Modulator::angle_delta_ = 0.0f private
Referenced by encodeString().
samples_per_symbol_
uint32_t signal_easel::psk::Modulator::samples_per_symbol_ = 0 private
Referenced by encodeString().
audio_buffer_
std::vector<int16_t> signal_easel::Modulator::audio_buffer_ = {} protected inherited
Referenced by signal_easel::Modulator::addAudioSample(), signal_easel::Modulator::addAudioSampleDouble(), signal_easel::Modulator::clearBuffer(), encodeBpsk(), encodeQpsk(), signal_easel::Modulator::writeToFile(), and signal_easel::Modulator::writeToPulseAudio().
sine_wave_phase_
double signal_easel::Modulator::sine_wave_phase_ = 0.0 private inherited
Used with addSineWave to keep a continuous phase between calls.
Referenced by signal_easel::Modulator::addSineWave(), and signal_easel::Modulator::clearBuffer().
The documentation for this class was generated from the following files:
psk.hpp
psk_modulator.cpp