Signal Easel: signal_easel::afsk::Receiver Class Reference
signal_easel::afsk::Receiver Class Reference
For receiving AFSK signals via a pulse audio stream.
#include <afsk.hpp>
Public Member Functions
Receiver (afsk::Settings settings=afsk::Settings())
~Receiver ()=default
uint64_t getLatency () const
double getVolume () const
void process () override
Protected Member Functions
virtual void decode ()
bool detectSignal (const PulseAudioBuffer &audio_buffer)
Protected Attributes
afsk::Settings afsk_settings_
afsk::Demodulator demodulator_
PulseAudioReader pulse_audio_reader_ {}
std::vector< int16_t > receive_buffer_ {}
Settings settings_
Detailed Description
For receiving AFSK signals via a pulse audio stream.
Constructor & Destructor Documentation
Receiver()
signal_easel::afsk::Receiver::Receiver (afsk::Settings settings = afsk::Settings()) inline
~Receiver()
signal_easel::afsk::Receiver::~Receiver () virtual default
Reimplemented from signal_easel::Receiver.
Member Function Documentation
process()
void signal_easel::afsk::Receiver::process () override virtual
Implements signal_easel::Receiver.
References detectSignal(), signal_easel::PulseAudioReader::getAudioBuffer(), signal_easel::PulseAudioReader::process(), and signal_easel::Receiver::pulse_audio_reader_.
Referenced by main().
detectSignal()
bool signal_easel::afsk::Receiver::detectSignal (const PulseAudioBuffer & audio_buffer) protected
References signal_easel::afsk::AFSK_RECEIVED_MIN_SAMPLES, and signal_easel::afsk::AFSK_SNR_THRESHOLD.
Referenced by process().
decode()
void signal_easel::afsk::Receiver::decode () protected virtual
Reimplemented in signal_easel::aprs::Receiver.
References signal_easel::afsk::Demodulator::NO_EOT, signal_easel::afsk::Demodulator::NO_SYN, and signal_easel::afsk::Demodulator::SUCCESS.
getLatency()
uint64_t signal_easel::Receiver::getLatency () const inline inherited
References signal_easel::PulseAudioReader::getLatency(), and signal_easel::Receiver::pulse_audio_reader_.
getVolume()
double signal_easel::Receiver::getVolume () const inline inherited
References signal_easel::PulseAudioReader::getVolume(), and signal_easel::Receiver::pulse_audio_reader_.
Member Data Documentation
demodulator_
afsk::Demodulator signal_easel::afsk::Receiver::demodulator_ protected
Referenced by signal_easel::aprs::Receiver::decode().
afsk_settings_
afsk::Settings signal_easel::afsk::Receiver::afsk_settings_ protected
receive_buffer_
std::vector<int16_t> signal_easel::afsk::Receiver::receive_buffer_ {} protected
pulse_audio_reader_
PulseAudioReader signal_easel::Receiver::pulse_audio_reader_ {} protected inherited
Referenced by signal_easel::Receiver::getLatency(), signal_easel::Receiver::getVolume(), and process().
settings_
Settings signal_easel::Receiver::settings_ protected inherited