SignalEasel: signal_easel::aprs::telemetry::TelemetryTranscoder Class Reference
signal_easel::aprs::telemetry::TelemetryTranscoder Class Reference
A class for encoding and decoding APRS telemetry messages.
#include <telemetry_transcoder.hpp>
Static Public Member Functions
static bool decodeMessage (TelemetryData &data, const std::vector< uint8_t > &message)
Takes in the information field of an APRS telemetry message and decodes it with the appropriate method.
static bool encodeBitSenseMessage (const TelemetryData &data, std::vector< uint8_t > &output)
Encodes the bit sense and project name into a message.
static bool encodeDataReportMessage (const TelemetryData &data, std::vector< uint8_t > &output)
Encodes the parameter data into a data report message.
static bool encodeParameterCoefficientMessage (const TelemetryData &data, std::vector< uint8_t > &output)
Encodes the parameter coefficients into a message.
static bool encodeParameterNameMessage (const TelemetryData &data, std::vector< uint8_t > &output)
Encodes the parameter names into a message.
static bool encodeUnitAndLabelMessage (const TelemetryData &data, std::vector< uint8_t > &output)
Encodes the parameter units and labels into a message.
Static Private Member Functions
static void addTelemetryStationAddress (const TelemetryData &data, std::vector< uint8_t > &output)
Used in the encode methods to add the telemetry station address to the message in the format ":N0CALL-1 :".
static bool decodeBitSenseMessage (TelemetryData &data, const std::vector< uint8_t > &message)
Decode the bit sense / project name message.
static bool decodeDataReportMessage (TelemetryData &data, const std::vector< uint8_t > &message)
Decode a data report message.
static bool decodeParameterCoefficientMessage (TelemetryData &data, const std::vector< uint8_t > &message)
Decode the parameter coefficients message.
static bool decodeParameterDescriptor (TelemetryData &data, const std::vector< uint8_t > &message, const bool name_or_unit)
Decode a name or unit/label message. They're the same format.
static bool decodeValidateHeader (const std::vector< uint8_t > &message, const std::string &header)
Validate the first few bytes of a message.
Detailed Description
A class for encoding and decoding APRS telemetry messages.
Member Function Documentation
encodeDataReportMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::encodeDataReportMessage (const TelemetryData & data, std::vector< uint8_t > & output) static
Encodes the parameter data into a data report message.
Parameters
data - The telemetry data to encode.
[out] output - The encoded message. This will be cleared before encoding.
Returns
true if the message was successfully encoded, false otherwise.
References signal_easel::aprs::telemetry::TelemetryData::getAnalogParametersConst(), signal_easel::aprs::telemetry::TelemetryData::getComment(), signal_easel::aprs::telemetry::TelemetryData::getDigitalParametersConst(), and signal_easel::aprs::telemetry::TelemetryData::getSequenceNumberString().
Referenced by signal_easel::aprs::TelemetryPacket::encode().
encodeParameterCoefficientMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::encodeParameterCoefficientMessage (const TelemetryData & data, std::vector< uint8_t > & output) static
Encodes the parameter coefficients into a message.
Parameters
data - The telemetry data to encode.
[out] output - The encoded message. This will be cleared before encoding.
Returns
true if the message was successfully encoded, false otherwise.
References addTelemetryStationAddress(), and signal_easel::aprs::telemetry::TelemetryData::getAnalogParametersConst().
Referenced by signal_easel::aprs::TelemetryPacket::encode().
encodeParameterNameMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::encodeParameterNameMessage (const TelemetryData & data, std::vector< uint8_t > & output) static
Encodes the parameter names into a message.
Parameters
data - The telemetry data to encode.
[out] output - The encoded message. This will be cleared before encoding.
Returns
true if the message was successfully encoded, false otherwise.
References addTelemetryStationAddress(), signal_easel::aprs::telemetry::TelemetryData::getAnalogParametersConst(), and signal_easel::aprs::telemetry::TelemetryData::getDigitalParametersConst().
Referenced by signal_easel::aprs::TelemetryPacket::encode().
encodeUnitAndLabelMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::encodeUnitAndLabelMessage (const TelemetryData & data, std::vector< uint8_t > & output) static
Encodes the parameter units and labels into a message.
Parameters
data - The telemetry data to encode.
[out] output - The encoded message. This will be cleared before encoding.
Returns
true if the message was successfully encoded, false otherwise.
References addTelemetryStationAddress(), signal_easel::aprs::telemetry::TelemetryData::getAnalogParametersConst(), and signal_easel::aprs::telemetry::TelemetryData::getDigitalParametersConst().
Referenced by signal_easel::aprs::TelemetryPacket::encode().
encodeBitSenseMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::encodeBitSenseMessage (const TelemetryData & data, std::vector< uint8_t > & output) static
Encodes the bit sense and project name into a message.
Parameters
data - The telemetry data to encode.
[out] output - The encoded message. This will be cleared before encoding.
Returns
true if the message was successfully encoded, false otherwise.
References addTelemetryStationAddress(), signal_easel::aprs::telemetry::TelemetryData::getDigitalParametersConst(), and signal_easel::aprs::telemetry::TelemetryData::getProjectTitle().
Referenced by signal_easel::aprs::TelemetryPacket::encode().
decodeMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::decodeMessage (TelemetryData & data, const std::vector< uint8_t > & message) static
Takes in the information field of an APRS telemetry message and decodes it with the appropriate method.
Parameters
data - The telemetry data to encode.
message - The information field of the APRS telemetry message.
Returns
true if the message was successfully decoded, false otherwise.
References decodeBitSenseMessage(), decodeDataReportMessage(), decodeParameterCoefficientMessage(), decodeParameterDescriptor(), signal_easel::aprs::telemetry::TelemetryData::setTelemetryStationAddress(), and signal_easel::aprs::telemetry::TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH.
Referenced by signal_easel::aprs::Demodulator::parseTelemetryPacket().
addTelemetryStationAddress()
void signal_easel::aprs::telemetry::TelemetryTranscoder::addTelemetryStationAddress (const TelemetryData & data, std::vector< uint8_t > & output) static private
Used in the encode methods to add the telemetry station address to the message in the format ":N0CALL-1 :".
Parameters
data - The input telemetry data, which contains the address.
[out] output - The message to add the address to.
References signal_easel::aprs::telemetry::TelemetryData::getTelemetryStationAddress(), signal_easel_validate, and signal_easel::aprs::telemetry::TelemetryData::TELEMETRY_STATION_ADDRESS_MAX_LENGTH_.
Referenced by encodeBitSenseMessage(), encodeParameterCoefficientMessage(), encodeParameterNameMessage(), and encodeUnitAndLabelMessage().
decodeValidateHeader()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::decodeValidateHeader (const std::vector< uint8_t > & message, const std::string & header) static private
Validate the first few bytes of a message.
Parameters
message - The message to validate.
header - The header to validate against, ex: "PARM."
Returns
true if the header matches, false if not.
References signal_easel::aprs::telemetry::TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH.
Referenced by decodeBitSenseMessage(), decodeParameterCoefficientMessage(), and decodeParameterDescriptor().
decodeDataReportMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::decodeDataReportMessage (TelemetryData & data, const std::vector< uint8_t > & message) static private
Decode a data report message.
Parameters
[out] data - The telemetry data object to populate.
message - The message to decode.
Returns
true if the message was decoded, false if not.
References signal_easel::aprs::telemetry::TelemetryData::COMMENT_MAX_LENGTH_, signal_easel::aprs::telemetry::TelemetryData::getAnalogParameters(), signal_easel::aprs::telemetry::TelemetryData::getDigitalParameters(), signal_easel::aprs::telemetry::TelemetryData::setComment(), and signal_easel::aprs::telemetry::TelemetryData::setSequenceNumber().
Referenced by decodeMessage().
decodeParameterDescriptor()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterDescriptor (TelemetryData & data, const std::vector< uint8_t > & message, const bool name_or_unit) static private
Decode a name or unit/label message. They're the same format.
Parameters
[out] data - The telemetry data object to populate.
message - The message to decode.
name_or_unit - true if decoding a name, false if decoding a unit or label.
Returns
true if the message was decoded, false if not.
References decodeValidateHeader(), signal_easel::aprs::telemetry::TelemetryData::getAnalogParameters(), signal_easel::aprs::telemetry::TelemetryData::getDigitalParameters(), and signal_easel::aprs::telemetry::TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH.
Referenced by decodeMessage().
decodeParameterCoefficientMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterCoefficientMessage (TelemetryData & data, const std::vector< uint8_t > & message) static private
Decode the parameter coefficients message.
Parameters
[out] data - The telemetry data object to populate.
message - The message to decode.
Returns
true if the message was decoded, false if not.
References decodeValidateHeader(), signal_easel::aprs::telemetry::TelemetryData::getAnalogParameters(), signal_easel::aprs::telemetry::TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH, and signal_easel::aprs::telemetry::validateCoefficient().
Referenced by decodeMessage().
decodeBitSenseMessage()
bool signal_easel::aprs::telemetry::TelemetryTranscoder::decodeBitSenseMessage (TelemetryData & data, const std::vector< uint8_t > & message) static private
Decode the bit sense / project name message.
Parameters
[out] data - The telemetry data object to populate.
message - The message to decode.
Returns
true if the message was decoded, false if not.
References decodeValidateHeader(), signal_easel::aprs::telemetry::TelemetryData::getDigitalParameters(), signal_easel::aprs::telemetry::TelemetryData::setProjectTitle(), and signal_easel::aprs::telemetry::TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH.
Referenced by decodeMessage().
The documentation for this class was generated from the following files:
telemetry_transcoder.hpp
telemetry_transcoder.cpp