Signal Easel: signal_easel::ax25::Frame Class Reference
signal_easel::ax25::Frame Class Reference
#include <ax25.hpp>
Public Types
enum class Type : uint8_t { UI = 0x03 }
The frame type of the AX-25 frame.
Public Member Functions
Frame ()=default
std::vector< uint8_t > buildFrame ()
Builds all internal portions of the frame. Doesn't include the flags.
std::vector< uint8_t > encodeFrame ()
A step beyond buildFrame. This function builds the frame, does the bit stuffing, adds the flags, and NRZI encodes the frame.
bool isFrameValid ()
bool parseBitStream (BitStream &bit_stream)
Attempt to parse an incoming bit stream into an AX.25 frame.
void setDestinationAddress (Address address)
setters/getters for the frame.
Address getDestinationAddress () const
void setSourceAddress (Address address)
Address getSourceAddress () const
void addRepeaterAddress (Address address)
std::vector< Address > getRepeaterAddresses () const
void setInformation (std::vector< uint8_t > information)
std::vector< uint8_t > getInformation () const
Private Member Functions
void AddByteForFcs (uint8_t byte)
void addToBuildBuffer (uint8_t byte, bool reverse=true)
uint16_t calculateFcsOnBuildBuffer ()
Private Attributes
std::vector< uint8_t > build_buffer_ = {}
Address destination_address_ = Address()
uint16_t fcs_ = 0xFFFF
std::vector< uint8_t > information_ = {}
uint8_t pid_ = K_PID
std::vector< Address > repeater_addresses_ = {}
Address source_address_ = Address()
Type type_ = Type::UI
Friends
std::ostream & operator<< (std::ostream &os, const Frame &address)
Member Enumeration Documentation
Type
enum signal_easel::ax25::Frame::Type : uint8_t strong
The frame type of the AX-25 frame.
There are three main frame types: Information, Supervisory, and Unnumbered. Currently only Unnumbered Information frames are supported.
Enumerator
UI
Constructor & Destructor Documentation
Frame()
signal_easel::ax25::Frame::Frame () default
Member Function Documentation
setDestinationAddress()
void signal_easel::ax25::Frame::setDestinationAddress (Address address)
setters/getters for the frame.
Exceptions
signal_easel::Exception Thrown with specific error code upon invalid input.
References signal_easel::ax25::Address::assertIsValid(), and destination_address_.
Referenced by signal_easel::aprs::AddRequiredFields(), main(), parseBitStream(), and TEST().
getDestinationAddress()
Address signal_easel::ax25::Frame::getDestinationAddress () const inline
References destination_address_.
setSourceAddress()
void signal_easel::ax25::Frame::setSourceAddress (Address address)
References signal_easel::ax25::Address::assertIsValid(), and source_address_.
Referenced by signal_easel::aprs::AddRequiredFields(), main(), parseBitStream(), and TEST().
getSourceAddress()
Address signal_easel::ax25::Frame::getSourceAddress () const inline
References source_address_.
addRepeaterAddress()
void signal_easel::ax25::Frame::addRepeaterAddress (Address address)
References signal_easel::ax25::Address::assertIsValid(), signal_easel::ax25::K_MAX_REPEATER_ADDRESSES, and repeater_addresses_.
Referenced by main(), and parseBitStream().
getRepeaterAddresses()
std::vector<Address> signal_easel::ax25::Frame::getRepeaterAddresses () const inline
References repeater_addresses_.
setInformation()
void signal_easel::ax25::Frame::setInformation (std::vector< uint8_t > information)
References information_, and signal_easel::ax25::K_MAX_INFORMATION_LENGTH.
Referenced by signal_easel::aprs::encodePacket(), and main().
getInformation()
std::vector<uint8_t> signal_easel::ax25::Frame::getInformation () const inline
References information_.
Referenced by signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Demodulator::parseExperimentalPacket(), signal_easel::aprs::Demodulator::parseMessagePacket(), and signal_easel::aprs::Demodulator::parsePositionPacket().
isFrameValid()
bool signal_easel::ax25::Frame::isFrameValid ()
References destination_address_, information_, signal_easel::ax25::Address::isValid(), signal_easel::ax25::K_MAX_INFORMATION_LENGTH, signal_easel::ax25::K_MAX_REPEATER_ADDRESSES, repeater_addresses_, and source_address_.
Referenced by buildFrame(), and TEST().
buildFrame()
std::vector< uint8_t > signal_easel::ax25::Frame::buildFrame ()
Builds all internal portions of the frame. Doesn't include the flags.
Returns
std::vector<uint8_t> The built frame
References build_buffer_, signal_easel::ax25::calculateFcs(), destination_address_, signal_easel::ax25::Address::encodeAddress(), fcs_, information_, isFrameValid(), pid_, repeater_addresses_, signal_easel::ax25::Address::setIsLastAddress(), source_address_, and type_.
Referenced by encodeFrame().
encodeFrame()
std::vector< uint8_t > signal_easel::ax25::Frame::encodeFrame ()
A step beyond buildFrame. This function builds the frame, does the bit stuffing, adds the flags, and NRZI encodes the frame.
Returns
std::vector<uint8_t>
References signal_easel::BitStream::addBits(), signal_easel::BitStream::addOneBit(), signal_easel::BitStream::addZeroBit(), buildFrame(), signal_easel::BitStream::getBitStreamLength(), signal_easel::ax25::K_FLAG, signal_easel::ax25::K_POSTAMBLE_LENGTH, signal_easel::ax25::K_PREAMBLE_LENGTH, and signal_easel::BitStream::popNextBit().
Referenced by signal_easel::aprs::encodePacket(), and main().
parseBitStream()
bool signal_easel::ax25::Frame::parseBitStream (BitStream & bit_stream)
Attempt to parse an incoming bit stream into an AX.25 frame.
Parameters
bit_stream The bit stream to parse (NRZI encoded)
Returns
true if the frame was successfully parsed
false if the frame was not successfully parsed
References addRepeaterAddress(), signal_easel::ax25::decodeNrzi(), signal_easel::ax25::deStuffBytes(), fcs_, signal_easel::ax25::findStartFlags(), information_, setDestinationAddress(), and setSourceAddress().
Referenced by signal_easel::aprs::Demodulator::lookForAx25Packet().
addToBuildBuffer()
void signal_easel::ax25::Frame::addToBuildBuffer (uint8_t byte, bool reverse = true) private
References build_buffer_, and signal_easel::ax25::reverseByte().
calculateFcsOnBuildBuffer()
uint16_t signal_easel::ax25::Frame::calculateFcsOnBuildBuffer () private
AddByteForFcs()
void signal_easel::ax25::Frame::AddByteForFcs (uint8_t byte) private
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Frame & address) friend
Member Data Documentation
destination_address_
Address signal_easel::ax25::Frame::destination_address_ = Address() private
Referenced by buildFrame(), getDestinationAddress(), isFrameValid(), and setDestinationAddress().
source_address_
Address signal_easel::ax25::Frame::source_address_ = Address() private
Referenced by buildFrame(), getSourceAddress(), isFrameValid(), and setSourceAddress().
repeater_addresses_
std::vector<Address> signal_easel::ax25::Frame::repeater_addresses_ = {} private
Referenced by addRepeaterAddress(), buildFrame(), getRepeaterAddresses(), and isFrameValid().
type_
Type signal_easel::ax25::Frame::type_ = Type::UI private
Referenced by buildFrame().
pid_
uint8_t signal_easel::ax25::Frame::pid_ = K_PID private
Referenced by buildFrame().
information_
std::vector<uint8_t> signal_easel::ax25::Frame::information_ = {} private
Referenced by buildFrame(), getInformation(), isFrameValid(), parseBitStream(), and setInformation().
fcs_
uint16_t signal_easel::ax25::Frame::fcs_ = 0xFFFF private
Referenced by buildFrame(), and parseBitStream().
build_buffer_
std::vector<uint8_t> signal_easel::ax25::Frame::build_buffer_ = {} private
Referenced by addToBuildBuffer(), and buildFrame().