Signal Easel: signal_easel::sstv::Modulator Class Reference
signal_easel::sstv::Modulator Class Reference
SSTV Modulator.
#include <sstv.hpp>
Classes
struct YCbCr
Public Member Functions
Modulator (sstv::Settings settings=sstv::Settings())
Constructor for the SSTV Modulator.
~Modulator ()=default
void clearBuffer ()
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
void encodeImage (std::string input_image_path)
Encodes an image into SSTV audio.
void writeToFile (const std::string &filename)
Write the audio to a file.
void writeToPulseAudio ()
Write the audio to the default PulseAudio output device.
Protected Member Functions
void addAudioSample (int16_t sample)
Add a PCM sample to the audio buffer.
void addAudioSampleDouble (double sample)
Add a PCM sample to the audio buffer.
void addSilence (uint32_t duration_in_samples)
Add silence to the audio buffer.
void addSineWave (uint16_t frequency, uint16_t num_samples)
Add a sine wave to the audio buffer.
Protected Attributes
std::vector< int16_t > audio_buffer_ = {}
Private Types
enum class ColorFormat { _4_2_0_ , _4_2_2_ , NONE }
enum class ColorType { Y , Cb , Cr }
Private Member Functions
void addMorseCode (const std::string &input_string)
Add morse code to the output audio.
void addPreamble ()
void encodeAdjustedImage (SstvImage &image)
void encodeScanLine (uint32_t line_number)
void pulse (double length, int frequency)
void readImageLine (SstvImage &image, uint32_t line_number)
void writeBuffer (const double total_time, ColorType ycbcr_colors)
Private Attributes
double c_scan_line_time_ = 0
ColorFormat color_format_ = ColorFormat::NONE
int even_separation_pulse_frequency_ = 0
uint32_t line_width_ = 0
uint32_t num_of_lines_ = 0
int odd_separation_pulse_frequency_ = 0
double porch_frequency_ = 0
double porch_length_ms_ = 0
std::vector< YCbCr > scan_line_buffer_ = {}
double separation_pulse_length_ms_ = 0
sstv::Settings settings_
The settings for the modulator.
double sine_wave_phase_ = 0.0
Used with addSineWave to keep a continuous phase between calls.
SstvImage::Mode sstv_image_tools_mode = SstvImage::Mode::ROBOT_36_COLOR
double sync_porch_frequency_ = 0
double sync_porch_length_ms_ = 0
double sync_pulse_frequency_ = 0
double sync_pulse_length_ms_ = 0
uint8_t vis_code_ = 0
double y_scan_line_time_ = 0
Detailed Description
SSTV Modulator.
Member Enumeration Documentation
ColorFormat
enum signal_easel::sstv::Modulator::ColorFormat strong private
Enumerator
_4_2_0_
_4_2_2_
NONE
ColorType
enum signal_easel::sstv::Modulator::ColorType strong private
Enumerator
Y
Cb
Cr
Constructor & Destructor Documentation
Modulator()
signal_easel::sstv::Modulator::Modulator (sstv::Settings settings = sstv::Settings())
Constructor for the SSTV Modulator.
Parameters
settings The settings for the modulator
References _4_2_0_, c_scan_line_time_, color_format_, even_separation_pulse_frequency_, line_width_, signal_easel::sstv::Settings::mode, num_of_lines_, odd_separation_pulse_frequency_, porch_frequency_, porch_length_ms_, signal_easel::sstv::Settings::ROBOT36_COLOR, separation_pulse_length_ms_, sstv_image_tools_mode, signal_easel::Exception::SSTV_MODE_NOT_IMPLEMENTED, sync_porch_frequency_, sync_porch_length_ms_, sync_pulse_frequency_, sync_pulse_length_ms_, vis_code_, and y_scan_line_time_.
~Modulator()
signal_easel::sstv::Modulator::~Modulator () virtual default
Reimplemented from signal_easel::Modulator.
Member Function Documentation
encodeImage()
void signal_easel::sstv::Modulator::encodeImage (std::string input_image_path)
Encodes an image into SSTV audio.
Parameters
input_image_path The path to the image to encode
Exceptions
signal_easel::Exception Thrown on failure
References addPreamble(), signal_easel::Settings::call_sign, encodeAdjustedImage(), line_width_, num_of_lines_, signal_easel::sstv::Settings::overlay_call_sign, scan_line_buffer_, settings_, signal_easel::Exception::SSTV_IMAGE_SIZE_MISMATCH, signal_easel::Exception::SSTV_IMAGE_TOOLS_ERROR, and sstv_image_tools_mode.
Referenced by TEST().
addPreamble()
void signal_easel::sstv::Modulator::addPreamble () private
References pulse(), and vis_code_.
Referenced by encodeImage().
encodeAdjustedImage()
void signal_easel::sstv::Modulator::encodeAdjustedImage (SstvImage & image) private
References encodeScanLine(), num_of_lines_, and readImageLine().
Referenced by encodeImage().
readImageLine()
void signal_easel::sstv::Modulator::readImageLine (SstvImage & image, uint32_t line_number) private
References _4_2_0_, _4_2_2_, signal_easel::sstv::Modulator::YCbCr::cb, color_format_, signal_easel::sstv::Modulator::YCbCr::cr, line_width_, scan_line_buffer_, signal_easel::Exception::SSTV_COLOR_FORMAT_NOT_IMPLEMENTED, signal_easel::Exception::SSTV_GET_PIXEL_FAILED, signal_easel::Exception::SSTV_SCAN_LINE_BUFFER_SIZE_MISMATCH, and signal_easel::sstv::Modulator::YCbCr::y.
Referenced by encodeAdjustedImage().
encodeScanLine()
void signal_easel::sstv::Modulator::encodeScanLine (uint32_t line_number) private
References c_scan_line_time_, Cb, Cr, even_separation_pulse_frequency_, odd_separation_pulse_frequency_, porch_frequency_, porch_length_ms_, pulse(), separation_pulse_length_ms_, sync_porch_frequency_, sync_porch_length_ms_, sync_pulse_frequency_, sync_pulse_length_ms_, writeBuffer(), Y, and y_scan_line_time_.
Referenced by encodeAdjustedImage().
pulse()
void signal_easel::sstv::Modulator::pulse (double length, int frequency) private
References signal_easel::Modulator::addSineWave(), and signal_easel::AUDIO_SAMPLE_RATE.
Referenced by addPreamble(), and encodeScanLine().
writeBuffer()
void signal_easel::sstv::Modulator::writeBuffer (const double total_time, ColorType ycbcr_colors) private
References signal_easel::Modulator::addSineWave(), signal_easel::AUDIO_SAMPLE_RATE, Cb, signal_easel::sstv::ColorToFreq(), Cr, line_width_, scan_line_buffer_, signal_easel::Exception::SSTV_INVALID_COLOR_TYPE, and Y.
Referenced by encodeScanLine().
clearBuffer()
void signal_easel::Modulator::clearBuffer () inherited
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Settings::NONE, signal_easel::Modulator::settings_, and signal_easel::Modulator::sine_wave_phase_.
Referenced by signal_easel::Modulator::Modulator().
writeToFile()
void signal_easel::Modulator::writeToFile (const std::string & filename) inherited
Write the audio to a file.
Parameters
filename The name/path of the file to write to
Exceptions
MWAVException Throws an exception if the file cannot be opened or if there is no data to write
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Settings::AFTER, signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::FILE_OPEN_ERROR, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Exception::NO_DATA_TO_WRITE, signal_easel::Settings::NONE, and signal_easel::Modulator::settings_.
Referenced by TEST().
writeToPulseAudio()
void signal_easel::Modulator::writeToPulseAudio () inherited
Write the audio to the default PulseAudio output device.
References signal_easel::Modulator::audio_buffer_, signal_easel::PULSE_AUDIO_APP_NAME, signal_easel::Exception::PULSE_AUDIO_DISABLED, signal_easel::PULSE_AUDIO_SAMPLE_SPEC, signal_easel::Exception::PULSE_DRAIN_ERROR, signal_easel::Exception::PULSE_OPEN_ERROR, and signal_easel::Exception::PULSE_WRITE_ERROR.
Referenced by main().
addAudioSample()
void signal_easel::Modulator::addAudioSample (int16_t sample) inline protected inherited
Add a PCM sample to the audio buffer.
Parameters
sample The PCM sample to add
References signal_easel::Modulator::audio_buffer_.
Referenced by signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), and signal_easel::afsk::Modulator::encodeBytes().
addAudioSampleDouble()
void signal_easel::Modulator::addAudioSampleDouble (double sample) inline protected inherited
Add a PCM sample to the audio buffer.
Parameters
sample The PCM sample to add - -1.0 to 1.0
References signal_easel::Modulator::audio_buffer_.
addSilence()
void signal_easel::Modulator::addSilence (uint32_t duration_in_samples) inline protected inherited
Add silence to the audio buffer.
Parameters
duration_in_samples
References signal_easel::Modulator::addAudioSample().
Referenced by signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
addSineWave()
void signal_easel::Modulator::addSineWave (uint16_t frequency, uint16_t num_samples) protected inherited
Add a sine wave to the audio buffer.
Parameters
frequency The frequency of the sine wave in Hz
num_samples The number of samples to add
References signal_easel::Modulator::addAudioSample(), signal_easel::Settings::amplitude, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::MAX_SAMPLE_VALUE, signal_easel::Modulator::settings_, signal_easel::Modulator::sine_wave_phase_, and signal_easel::TWO_PI_VAL.
Referenced by signal_easel::Modulator::addMorseCode(), pulse(), and writeBuffer().
addMorseCode()
void signal_easel::Modulator::addMorseCode (const std::string & input_string) private inherited
Add morse code to the output audio.
Parameters
input_string the string to convert to morse code
References signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), signal_easel::DASH_LENGTH, signal_easel::DOT_LENGTH, signal_easel::Exception::EMPTY_INPUT_STRING, signal_easel::Exception::INVALID_MORSE_CHAR, signal_easel::LETTER_SPACE_LENGTH, signal_easel::MORSE_CODE_MAP, signal_easel::MORSE_TONE_FREQUENCY, and signal_easel::TIME_BETWEEN_SYMBOLS.
Referenced by signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
Member Data Documentation
settings_
sstv::Settings signal_easel::sstv::Modulator::settings_ private
The settings for the modulator.
Referenced by encodeImage().
sstv_image_tools_mode
SstvImage::Mode signal_easel::sstv::Modulator::sstv_image_tools_mode = SstvImage::Mode::ROBOT_36_COLOR private
Referenced by Modulator(), and encodeImage().
color_format_
ColorFormat signal_easel::sstv::Modulator::color_format_ = ColorFormat::NONE private
Referenced by Modulator(), and readImageLine().
line_width_
uint32_t signal_easel::sstv::Modulator::line_width_ = 0 private
Referenced by Modulator(), encodeImage(), readImageLine(), and writeBuffer().
num_of_lines_
uint32_t signal_easel::sstv::Modulator::num_of_lines_ = 0 private
Referenced by Modulator(), encodeAdjustedImage(), and encodeImage().
vis_code_
uint8_t signal_easel::sstv::Modulator::vis_code_ = 0 private
Referenced by Modulator(), and addPreamble().
y_scan_line_time_
double signal_easel::sstv::Modulator::y_scan_line_time_ = 0 private
Referenced by Modulator(), and encodeScanLine().
c_scan_line_time_
double signal_easel::sstv::Modulator::c_scan_line_time_ = 0 private
Referenced by Modulator(), and encodeScanLine().
sync_pulse_length_ms_
double signal_easel::sstv::Modulator::sync_pulse_length_ms_ = 0 private
Referenced by Modulator(), and encodeScanLine().
sync_pulse_frequency_
double signal_easel::sstv::Modulator::sync_pulse_frequency_ = 0 private
Referenced by Modulator(), and encodeScanLine().
sync_porch_length_ms_
double signal_easel::sstv::Modulator::sync_porch_length_ms_ = 0 private
Referenced by Modulator(), and encodeScanLine().
sync_porch_frequency_
double signal_easel::sstv::Modulator::sync_porch_frequency_ = 0 private
Referenced by Modulator(), and encodeScanLine().
separation_pulse_length_ms_
double signal_easel::sstv::Modulator::separation_pulse_length_ms_ = 0 private
Referenced by Modulator(), and encodeScanLine().
even_separation_pulse_frequency_
int signal_easel::sstv::Modulator::even_separation_pulse_frequency_ = 0 private
Referenced by Modulator(), and encodeScanLine().
odd_separation_pulse_frequency_
int signal_easel::sstv::Modulator::odd_separation_pulse_frequency_ = 0 private
Referenced by Modulator(), and encodeScanLine().
porch_length_ms_
double signal_easel::sstv::Modulator::porch_length_ms_ = 0 private
Referenced by Modulator(), and encodeScanLine().
porch_frequency_
double signal_easel::sstv::Modulator::porch_frequency_ = 0 private
Referenced by Modulator(), and encodeScanLine().
scan_line_buffer_
std::vector<YCbCr> signal_easel::sstv::Modulator::scan_line_buffer_ = {} private
Referenced by encodeImage(), readImageLine(), and writeBuffer().
audio_buffer_
std::vector<int16_t> signal_easel::Modulator::audio_buffer_ = {} protected inherited
Referenced by signal_easel::Modulator::addAudioSample(), signal_easel::Modulator::addAudioSampleDouble(), signal_easel::Modulator::clearBuffer(), signal_easel::psk::Modulator::encodeBpsk(), signal_easel::psk::Modulator::encodeQpsk(), signal_easel::Modulator::writeToFile(), and signal_easel::Modulator::writeToPulseAudio().
sine_wave_phase_
double signal_easel::Modulator::sine_wave_phase_ = 0.0 private inherited
Used with addSineWave to keep a continuous phase between calls.
Referenced by signal_easel::Modulator::addSineWave(), and signal_easel::Modulator::clearBuffer().