SignalEasel: signal_easel::aprs::telemetry::TelemetryData Class Reference
signal_easel::aprs::telemetry::TelemetryData Class Reference
A container for telemetry data. Contains all of the components of APRS telemetry messages.
#include <telemetry_data.hpp>
Public Member Functions
TelemetryData ()
Construct a new TelemetryData object.
virtual ~TelemetryData ()=default
Destroy the TelemetryData object.
AnalogParameter & getAnalog (Parameter::Id id)
Access an analog parameter.
std::array< AnalogParameter, 5 > & getAnalogParameters ()
const std::array< AnalogParameter, 5 > & getAnalogParametersConst () const
std::string getComment () const
Get the comment.
DigitalParameter & getDigital (Parameter::Id id)
Access a digital parameter.
std::array< DigitalParameter, 8 > & getDigitalParameters ()
const std::array< DigitalParameter, 8 > & getDigitalParametersConst () const
std::string getProjectTitle () const
Get the project title.
uint16_t getSequenceNumber () const
Get the sequence number.
std::string getSequenceNumberString () const
Get the sequence number as a string of 3 digits.
std::string getTelemetryStationAddress () const
Get the address of the station that is sending the telemetry data.
bool setComment (const std::string &comment)
Set the comment. Must be less than 220 characters. If the comment is too long, it will be truncated.
bool setProjectTitle (const std::string &project_title)
Set the project title. Must be less than 23 characters. If the project title is too long, it will be truncated.
bool setSequenceNumber (uint16_t sequence_number)
Set the sequence number. Must be less than 1000. If the sequence number is greater than 999, it will be set to 0.
void setTelemetryStationAddress (const std::string &address)
Set the address of the station that is sending the telemetry data for use in the parameter name, unit/label, equation, and bit sense messages.
void setTelemetryStationAddress (const std::string &address, uint8_t ssid)
Set the address of the station that is sending the telemetry data for use in the parameter name, unit/label, equation, and bit sense messages.
Static Public Attributes
static constexpr size_t COMMENT_MAX_LENGTH_ = 220
The maximum length of the comment within the data report message.
static constexpr size_t PROJECT_TITLE_MAX_LENGTH_ = 23 - 1
The maximum length of the project title within the bit sense message. This number is 23, but we need to account for the comma.
static constexpr size_t SEQUENCE_NUMBER_MAX_ = 999
The maximum sequence number.
static constexpr size_t TELEMETRY_STATION_ADDRESS_MAX_LENGTH_ = 9
The maximum length of the telemetry station address including the SSID. APRS 1.0 Chapter 13 "On-Air Definition of Telemetry Parameters".
Private Attributes
std::array< AnalogParameter, 5 > analog_parameters_
The analog parameters.
std::string comment_ {""}
The comment that is attached to the end of the data report message.
std::array< DigitalParameter, 8 > digital_parameters_
The digital parameters.
std::string project_title_ {""}
The title of the project.
uint16_t sequence_number_ {0}
The sequence number of the data report message.
std::string telemetry_station_address_ {""}
The address of the station that is sending the telemetry data.
Detailed Description
A container for telemetry data. Contains all of the components of APRS telemetry messages.
Constructor & Destructor Documentation
TelemetryData()
signal_easel::aprs::telemetry::TelemetryData::TelemetryData ()
Construct a new TelemetryData object.
~TelemetryData()
virtual signal_easel::aprs::telemetry::TelemetryData::~TelemetryData () virtual default
Destroy the TelemetryData object.
Member Function Documentation
getAnalog()
AnalogParameter & signal_easel::aprs::telemetry::TelemetryData::getAnalog (Parameter::Id id)
Access an analog parameter.
Parameters
id - The ID of the parameter.
Returns
A reference to the analog parameter.
References signal_easel::aprs::telemetry::Parameter::Analog, analog_parameters_, signal_easel::aprs::telemetry::Parameter::getType(), and signal_easel_validate.
Referenced by TEST().
getDigital()
DigitalParameter & signal_easel::aprs::telemetry::TelemetryData::getDigital (Parameter::Id id)
Access a digital parameter.
Parameters
id - The ID of the parameter.
Returns
A reference to the digital parameter.
References signal_easel::aprs::telemetry::Parameter::B1, signal_easel::aprs::telemetry::Parameter::Digital, digital_parameters_, signal_easel::aprs::telemetry::Parameter::getType(), and signal_easel_validate.
Referenced by TEST().
setTelemetryStationAddress() [1/2]
void signal_easel::aprs::telemetry::TelemetryData::setTelemetryStationAddress (const std::string & address)
Set the address of the station that is sending the telemetry data for use in the parameter name, unit/label, equation, and bit sense messages.
Parameters
address - The address of the station including the SSID, e.g. "N0CALL-1". Must be 9 characters or less. There is no other enforcement of the address format.
Exceptions
signal_easel::Exception if the address is too long.
References signal_easel::Exception::APRS_INVALID_SOURCE_ADDRESS_LENGTH, telemetry_station_address_, and TELEMETRY_STATION_ADDRESS_MAX_LENGTH_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeMessage(), and TelemetryTranscoder_test::SetUp().
setTelemetryStationAddress() [2/2]
void signal_easel::aprs::telemetry::TelemetryData::setTelemetryStationAddress (const std::string & address, uint8_t ssid)
Set the address of the station that is sending the telemetry data for use in the parameter name, unit/label, equation, and bit sense messages.
Parameters
address - The address of the station excluding the SSID, e.g. "NOCALL". Must be 9 characters or less. There is no other enforcement of the address format.
ssid - The SSID of the station, in the range of 0-15.
References signal_easel::Exception::APRS_INVALID_SOURCE_ADDRESS_LENGTH, and telemetry_station_address_.
getTelemetryStationAddress()
std::string signal_easel::aprs::telemetry::TelemetryData::getTelemetryStationAddress () const inline
Get the address of the station that is sending the telemetry data.
Returns
The address of the station.
References telemetry_station_address_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::addTelemetryStationAddress().
setSequenceNumber()
bool signal_easel::aprs::telemetry::TelemetryData::setSequenceNumber (uint16_t sequence_number)
Set the sequence number. Must be less than 1000. If the sequence number is greater than 999, it will be set to 0.
Parameters
sequence_number - The sequence number.
References sequence_number_, and SEQUENCE_NUMBER_MAX_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeDataReportMessage(), and TEST().
getSequenceNumber()
uint16_t signal_easel::aprs::telemetry::TelemetryData::getSequenceNumber () const inline
Get the sequence number.
Returns
The sequence number.
References sequence_number_.
Referenced by TEST().
getSequenceNumberString()
std::string signal_easel::aprs::telemetry::TelemetryData::getSequenceNumberString () const
Get the sequence number as a string of 3 digits.
Returns
The sequence number as a string.
References sequence_number_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::encodeDataReportMessage(), and TEST().
setComment()
bool signal_easel::aprs::telemetry::TelemetryData::setComment (const std::string & comment)
Set the comment. Must be less than 220 characters. If the comment is too long, it will be truncated.
Parameters
comment - The comment.
Returns
true if the comment was set, false if the comment was too long.
References comment_, and COMMENT_MAX_LENGTH_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeDataReportMessage(), and TEST().
getComment()
std::string signal_easel::aprs::telemetry::TelemetryData::getComment () const inline
Get the comment.
Returns
The comment.
References comment_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::encodeDataReportMessage(), and TEST().
setProjectTitle()
bool signal_easel::aprs::telemetry::TelemetryData::setProjectTitle (const std::string & project_title)
Set the project title. Must be less than 23 characters. If the project title is too long, it will be truncated.
Parameters
project_title - The project title.
Returns
true if the project title was set, false if the project title was too long.
References project_title_, and PROJECT_TITLE_MAX_LENGTH_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeBitSenseMessage(), and TEST().
getProjectTitle()
std::string signal_easel::aprs::telemetry::TelemetryData::getProjectTitle () const inline
Get the project title.
Returns
The project title.
References project_title_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::encodeBitSenseMessage(), and TEST().
getAnalogParametersConst()
const std::array< AnalogParameter, 5 > & signal_easel::aprs::telemetry::TelemetryData::getAnalogParametersConst () const inline
References analog_parameters_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::encodeDataReportMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::encodeParameterCoefficientMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::encodeParameterNameMessage(), and signal_easel::aprs::telemetry::TelemetryTranscoder::encodeUnitAndLabelMessage().
getAnalogParameters()
std::array< AnalogParameter, 5 > & signal_easel::aprs::telemetry::TelemetryData::getAnalogParameters () inline
References analog_parameters_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeDataReportMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterCoefficientMessage(), and signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterDescriptor().
getDigitalParametersConst()
const std::array< DigitalParameter, 8 > & signal_easel::aprs::telemetry::TelemetryData::getDigitalParametersConst () const inline
References digital_parameters_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::encodeBitSenseMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::encodeDataReportMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::encodeParameterNameMessage(), and signal_easel::aprs::telemetry::TelemetryTranscoder::encodeUnitAndLabelMessage().
getDigitalParameters()
std::array< DigitalParameter, 8 > & signal_easel::aprs::telemetry::TelemetryData::getDigitalParameters () inline
References digital_parameters_.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeBitSenseMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::decodeDataReportMessage(), and signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterDescriptor().
Member Data Documentation
TELEMETRY_STATION_ADDRESS_MAX_LENGTH_
constexpr size_t signal_easel::aprs::telemetry::TelemetryData::TELEMETRY_STATION_ADDRESS_MAX_LENGTH_ = 9 static constexpr
The maximum length of the telemetry station address including the SSID. APRS 1.0 Chapter 13 "On-Air Definition of Telemetry Parameters".
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::addTelemetryStationAddress(), and setTelemetryStationAddress().
SEQUENCE_NUMBER_MAX_
constexpr size_t signal_easel::aprs::telemetry::TelemetryData::SEQUENCE_NUMBER_MAX_ = 999 static constexpr
The maximum sequence number.
Referenced by setSequenceNumber().
COMMENT_MAX_LENGTH_
constexpr size_t signal_easel::aprs::telemetry::TelemetryData::COMMENT_MAX_LENGTH_ = 220 static constexpr
The maximum length of the comment within the data report message.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeDataReportMessage(), and setComment().
PROJECT_TITLE_MAX_LENGTH_
constexpr size_t signal_easel::aprs::telemetry::TelemetryData::PROJECT_TITLE_MAX_LENGTH_ = 23 - 1 static constexpr
The maximum length of the project title within the bit sense message. This number is 23, but we need to account for the comma.
Referenced by setProjectTitle().
telemetry_station_address_
std::string signal_easel::aprs::telemetry::TelemetryData::telemetry_station_address_ {""} private
The address of the station that is sending the telemetry data.
Used in all telemetry messages other than the data report message. Example of where this is used: ":N0CALL-1 :PARM.x"
Referenced by getTelemetryStationAddress(), and setTelemetryStationAddress().
sequence_number_
uint16_t signal_easel::aprs::telemetry::TelemetryData::sequence_number_ {0} private
The sequence number of the data report message.
Referenced by getSequenceNumber(), getSequenceNumberString(), and setSequenceNumber().
comment_
std::string signal_easel::aprs::telemetry::TelemetryData::comment_ {""} private
The comment that is attached to the end of the data report message.
Referenced by getComment(), and setComment().
project_title_
std::string signal_easel::aprs::telemetry::TelemetryData::project_title_ {""} private
The title of the project.
Referenced by getProjectTitle(), and setProjectTitle().
analog_parameters_
std::array<AnalogParameter, 5> signal_easel::aprs::telemetry::TelemetryData::analog_parameters_ private
The analog parameters.
Referenced by getAnalog(), getAnalogParameters(), and getAnalogParametersConst().
digital_parameters_
std::array<DigitalParameter, 8> signal_easel::aprs::telemetry::TelemetryData::digital_parameters_ private
The digital parameters.
Referenced by getDigital(), getDigitalParameters(), and getDigitalParametersConst().
The documentation for this class was generated from the following files:
telemetry_data.hpp
telemetry_data.cpp