Signal Easel: signal_easel::afsk::Modulator Class Reference
signal_easel::afsk::Modulator Class Reference
Modulates data into an AFSK signal.
#include <afsk.hpp>
Public Member Functions
Modulator (afsk::Settings settings=afsk::Settings())
~Modulator ()=default
void addBytes (const std::vector< uint8_t > &data)
Add data to the audio buffer.
void addString (const std::string &data)
Add string data to the audio buffer.
void clearBuffer ()
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
void writeToFile (const std::string &filename)
Write the audio to a file.
void writeToPulseAudio ()
Write the audio to the default PulseAudio output device.
Protected Member Functions
void addAudioSample (int16_t sample)
Add a PCM sample to the audio buffer.
void addSilence (uint32_t duration_in_samples)
Add silence to the audio buffer.
void addSineWave (uint16_t frequency, uint16_t num_samples)
Add a sine wave to the audio buffer.
void encodeBytes (const std::vector< uint8_t > &input_bytes) override
This is overridden by the child classes to encode the data that is passed in by addBytes and addString.
Protected Attributes
std::vector< int16_t > audio_buffer_ = {}
Private Member Functions
void addMorseCode (const std::string &input_string)
Add morse code to the output audio.
void convertToNRZI (std::vector< uint8_t > &data)
Converts the data to NRZI for APRS mode.
Private Attributes
int8_t current_bipolar_bit_ = 0
int32_t integral_value_ = 0
bool nrzi_previous_tone_mark_ = false
int8_t previous_bipolar_bit_ = 0
afsk::Settings settings_
double sine_wave_phase_ = 0.0
Used with addSineWave to keep a continuous phase between calls.
Static Private Attributes
static constexpr double CENTER_OVER_SAMPLE_FREQ_
static constexpr double DELTA_OVER_SAMPLE_FREQ_
static constexpr uint32_t OVER_SAMPLE_FACTOR_ = 4
static constexpr uint32_t SAMPLE_FREQUENCY_
static constexpr uint32_t SAMPLES_PER_SYMBOL_
Detailed Description
Modulates data into an AFSK signal.
Constructor & Destructor Documentation
Modulator()
signal_easel::afsk::Modulator::Modulator (afsk::Settings settings = afsk::Settings()) inline
~Modulator()
signal_easel::afsk::Modulator::~Modulator () virtual default
Reimplemented from signal_easel::Modulator.
Member Function Documentation
encodeBytes()
void signal_easel::afsk::Modulator::encodeBytes (const std::vector< uint8_t > & data) override protected virtual
This is overridden by the child classes to encode the data that is passed in by addBytes and addString.
Parameters
data The data to encode and add to the audio buffer
"index" is the used to determine when to go to the next bit. It is not actually used as an index.
"prev_index" is the previous value of "index"
The index of the current bit in the vector of bytes
Implements signal_easel::DataModulator.
References signal_easel::Modulator::addAudioSample(), signal_easel::afsk::AFSK_ASCII_PREAMBLE_LENGTH, signal_easel::Settings::amplitude, CENTER_OVER_SAMPLE_FREQ_, current_bipolar_bit_, DELTA_OVER_SAMPLE_FREQ_, signal_easel::getBpBitAtIndex(), signal_easel::afsk::Settings::include_ascii_padding, integral_value_, signal_easel::MAX_SAMPLE_VALUE, signal_easel::Exception::NO_DATA_TO_WRITE, OVER_SAMPLE_FACTOR_, previous_bipolar_bit_, SAMPLE_FREQUENCY_, SAMPLES_PER_SYMBOL_, settings_, and signal_easel::TWO_PI_VAL.
convertToNRZI()
void signal_easel::afsk::Modulator::convertToNRZI (std::vector< uint8_t > & data) private
Converts the data to NRZI for APRS mode.
NRZI encoding (Non Return to Zero Inverted), 0 is encoded as a change in tone, while 1 is encoded as no change.
Parameters
data The data to convert
References signal_easel::isBitSet().
addBytes()
void signal_easel::DataModulator::addBytes (const std::vector< uint8_t > & data) inherited
Add data to the audio buffer.
Parameters
data The data to add
References signal_easel::DataModulator::encodeBytes().
addString()
void signal_easel::DataModulator::addString (const std::string & data) inherited
Add string data to the audio buffer.
Parameters
data The string to add
References signal_easel::DataModulator::encodeBytes().
Referenced by main(), and TEST().
clearBuffer()
void signal_easel::Modulator::clearBuffer () inherited
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Settings::NONE, signal_easel::Modulator::settings_, and signal_easel::Modulator::sine_wave_phase_.
Referenced by signal_easel::Modulator::Modulator().
writeToFile()
void signal_easel::Modulator::writeToFile (const std::string & filename) inherited
Write the audio to a file.
Parameters
filename The name/path of the file to write to
Exceptions
MWAVException Throws an exception if the file cannot be opened or if there is no data to write
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Settings::AFTER, signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::FILE_OPEN_ERROR, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Exception::NO_DATA_TO_WRITE, signal_easel::Settings::NONE, and signal_easel::Modulator::settings_.
Referenced by TEST().
writeToPulseAudio()
void signal_easel::Modulator::writeToPulseAudio () inherited
Write the audio to the default PulseAudio output device.
References signal_easel::Modulator::audio_buffer_, signal_easel::PULSE_AUDIO_APP_NAME, signal_easel::Exception::PULSE_AUDIO_DISABLED, signal_easel::PULSE_AUDIO_SAMPLE_SPEC, signal_easel::Exception::PULSE_DRAIN_ERROR, signal_easel::Exception::PULSE_OPEN_ERROR, and signal_easel::Exception::PULSE_WRITE_ERROR.
Referenced by main().
addAudioSample()
void signal_easel::Modulator::addAudioSample (int16_t sample) inline protected inherited
Add a PCM sample to the audio buffer.
Parameters
sample The PCM sample to add
References signal_easel::Modulator::audio_buffer_.
Referenced by signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), and encodeBytes().
addSilence()
void signal_easel::Modulator::addSilence (uint32_t duration_in_samples) inline protected inherited
Add silence to the audio buffer.
Parameters
duration_in_samples
References signal_easel::Modulator::addAudioSample().
Referenced by signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
addSineWave()
void signal_easel::Modulator::addSineWave (uint16_t frequency, uint16_t num_samples) protected inherited
Add a sine wave to the audio buffer.
Parameters
frequency The frequency of the sine wave in Hz
num_samples The number of samples to add
References signal_easel::Modulator::addAudioSample(), signal_easel::Settings::amplitude, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::MAX_SAMPLE_VALUE, signal_easel::Modulator::settings_, signal_easel::Modulator::sine_wave_phase_, and signal_easel::TWO_PI_VAL.
Referenced by signal_easel::Modulator::addMorseCode().
addMorseCode()
void signal_easel::Modulator::addMorseCode (const std::string & input_string) private inherited
Add morse code to the output audio.
Parameters
input_string the string to convert to morse code
References signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), signal_easel::DASH_LENGTH, signal_easel::DOT_LENGTH, signal_easel::Exception::EMPTY_INPUT_STRING, signal_easel::Exception::INVALID_MORSE_CHAR, signal_easel::LETTER_SPACE_LENGTH, signal_easel::MORSE_CODE_MAP, signal_easel::MORSE_TONE_FREQUENCY, and signal_easel::TIME_BETWEEN_SYMBOLS.
Referenced by signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
Member Data Documentation
settings_
afsk::Settings signal_easel::afsk::Modulator::settings_ private
Referenced by encodeBytes().
nrzi_previous_tone_mark_
bool signal_easel::afsk::Modulator::nrzi_previous_tone_mark_ = false private
current_bipolar_bit_
int8_t signal_easel::afsk::Modulator::current_bipolar_bit_ = 0 private
Referenced by encodeBytes().
previous_bipolar_bit_
int8_t signal_easel::afsk::Modulator::previous_bipolar_bit_ = 0 private
Referenced by encodeBytes().
integral_value_
int32_t signal_easel::afsk::Modulator::integral_value_ = 0 private
Referenced by encodeBytes().
OVER_SAMPLE_FACTOR_
constexpr uint32_t signal_easel::afsk::Modulator::OVER_SAMPLE_FACTOR_ = 4 static constexpr private
Referenced by encodeBytes().
SAMPLE_FREQUENCY_
constexpr uint32_t signal_easel::afsk::Modulator::SAMPLE_FREQUENCY_ static constexpr private
Initial value:
=
      AUDIO_SAMPLE_RATE * OVER_SAMPLE_FACTOR_
Referenced by encodeBytes().
SAMPLES_PER_SYMBOL_
constexpr uint32_t signal_easel::afsk::Modulator::SAMPLES_PER_SYMBOL_ static constexpr private
Initial value:
=
      SAMPLE_FREQUENCY_ / AFSK_BAUD_RATE
Referenced by encodeBytes().
CENTER_OVER_SAMPLE_FREQ_
constexpr double signal_easel::afsk::Modulator::CENTER_OVER_SAMPLE_FREQ_ static constexpr private
Initial value:
=
      static_cast<double>(AFSK_CENTER_FREQUENCY) / SAMPLE_FREQUENCY_
Referenced by encodeBytes().
DELTA_OVER_SAMPLE_FREQ_
constexpr double signal_easel::afsk::Modulator::DELTA_OVER_SAMPLE_FREQ_ static constexpr private
Initial value:
=
      static_cast<double>(AFSK_FREQUENCY_DEVIATION) / SAMPLE_FREQUENCY_
Referenced by encodeBytes().
audio_buffer_
std::vector<int16_t> signal_easel::Modulator::audio_buffer_ = {} protected inherited
Referenced by signal_easel::Modulator::addAudioSample(), signal_easel::Modulator::clearBuffer(), signal_easel::Modulator::writeToFile(), and signal_easel::Modulator::writeToPulseAudio().
sine_wave_phase_
double signal_easel::Modulator::sine_wave_phase_ = 0.0 private inherited
Used with addSineWave to keep a continuous phase between calls.
Referenced by signal_easel::Modulator::addSineWave(), and signal_easel::Modulator::clearBuffer().