Signal Easel: signal_easel::ax25::Address Class Reference
signal_easel::ax25::Address Class Reference
AX.25 Address class. For encoding and decoding AX.25 addresses.
#include <ax25.hpp>
Public Types
typedef std::array< uint8_t, 7 > AddressArray
Public Member Functions
Address ()=default
Address (AddressArray address_array)
Address (std::string address_string, uint8_t ssid, bool is_last_address=false)
void assertIsValid ()
Checks if the address is valid, if not throws an exception with a specific error code.
void decodeAddress (AddressArray address_array)
Decode an AX.25 address from it's byte array representation.
AddressArray encodeAddress ()
Get the address as a byte array.
std::string getAddressString () const
uint8_t getSsid () const
bool isAddressStringValid ()
bool isCommandOrResponse () const
Also used as the "Has been repeated" bit.
bool isLastAddress () const
bool isReservedBit1Set () const
bool isReservedBit2Set () const
bool isSsidValid ()
bool isValid ()
If the address is valid (can be encoded correctly or was decoded)
void setAddressString (std::string address_string)
Set the Address String object.
void setIsLastAddress (bool is_last_address)
Set the as the last address in the AX.25 frame (Sets a bit in the ssid byte)
void setSsid (uint8_t ssid)
Set the SSID (0-15)
Private Member Functions
void assertAddressStringIsValid ()
void assertSsidIsValid ()
Private Attributes
std::string address_string_ = ""
bool command_or_response_ = true
bool is_last_address_ = false
bool reserve_bit_1_ = true
bool reserve_bit_2_ = true
uint8_t ssid_ = 0x00
Friends
std::ostream & operator<< (std::ostream &os, const Address &address)
Detailed Description
AX.25 Address class. For encoding and decoding AX.25 addresses.
See AX.25 2.2 3.12.2 and 3.12.3
Member Typedef Documentation
AddressArray
typedef std::array<uint8_t, 7> signal_easel::ax25::Address::AddressArray
Constructor & Destructor Documentation
Address() [1/3]
signal_easel::ax25::Address::Address () default
Address() [2/3]
signal_easel::ax25::Address::Address (std::string address_string, uint8_t ssid, bool is_last_address = false)
References setAddressString(), setIsLastAddress(), and setSsid().
Address() [3/3]
signal_easel::ax25::Address::Address (AddressArray address_array)
References decodeAddress().
Member Function Documentation
setAddressString()
void signal_easel::ax25::Address::setAddressString (std::string address_string)
Set the Address String object.
Parameters
address_string The address string to set
Returns
true if the address string was successfully set
References address_string_, and assertAddressStringIsValid().
Referenced by Address().
getAddressString()
std::string signal_easel::ax25::Address::getAddressString () const inline
References address_string_.
Referenced by TEST().
setSsid()
void signal_easel::ax25::Address::setSsid (uint8_t ssid)
Set the SSID (0-15)
Parameters
ssid The 4 bit SSID to set
Returns
true if the SSID was successfully set/is valid
References assertSsidIsValid(), and ssid_.
Referenced by Address().
getSsid()
uint8_t signal_easel::ax25::Address::getSsid () const inline
References ssid_.
Referenced by TEST().
setIsLastAddress()
void signal_easel::ax25::Address::setIsLastAddress (bool is_last_address) inline
Set the as the last address in the AX.25 frame (Sets a bit in the ssid byte)
References is_last_address_.
Referenced by Address(), and signal_easel::ax25::Frame::buildFrame().
isLastAddress()
bool signal_easel::ax25::Address::isLastAddress () const inline
References is_last_address_.
Referenced by TEST().
isCommandOrResponse()
bool signal_easel::ax25::Address::isCommandOrResponse () const inline
Also used as the "Has been repeated" bit.
Returns
true
false
References command_or_response_.
Referenced by TEST().
isReservedBit1Set()
bool signal_easel::ax25::Address::isReservedBit1Set () const inline
References reserve_bit_1_.
Referenced by TEST().
isReservedBit2Set()
bool signal_easel::ax25::Address::isReservedBit2Set () const inline
References reserve_bit_2_.
Referenced by TEST().
decodeAddress()
void signal_easel::ax25::Address::decodeAddress (Address::AddressArray address_array)
Decode an AX.25 address from it's byte array representation.
Parameters
address_array The address to decode
Exceptions
signal_easel::Exception Thrown if the address/SSID is invalid
References address_string_, assertAddressStringIsValid(), assertSsidIsValid(), command_or_response_, is_last_address_, signal_easel::ax25::K_ADDRESS_CHARS_LENGTH, reserve_bit_1_, reserve_bit_2_, and ssid_.
Referenced by Address().
encodeAddress()
Address::AddressArray signal_easel::ax25::Address::encodeAddress ()
Get the address as a byte array.
Returns
AddressArray
References address_string_, assertIsValid(), command_or_response_, is_last_address_, signal_easel::ax25::K_ADDRESS_CHARS_LENGTH, reserve_bit_1_, reserve_bit_2_, and ssid_.
Referenced by signal_easel::ax25::Frame::buildFrame(), and TEST().
isValid()
bool signal_easel::ax25::Address::isValid ()
If the address is valid (can be encoded correctly or was decoded)
Returns
true if the address is valid false otherwise
References isAddressStringValid(), and isSsidValid().
Referenced by signal_easel::ax25::Frame::isFrameValid(), and TEST().
assertIsValid()
void signal_easel::ax25::Address::assertIsValid () inline
Checks if the address is valid, if not throws an exception with a specific error code.
References assertAddressStringIsValid(), and assertSsidIsValid().
Referenced by signal_easel::ax25::Frame::addRepeaterAddress(), encodeAddress(), signal_easel::ax25::Frame::setDestinationAddress(), signal_easel::ax25::Frame::setSourceAddress(), and TEST().
isSsidValid()
bool signal_easel::ax25::Address::isSsidValid ()
References signal_easel::ax25::K_MAX_SSID_VALUE, and ssid_.
Referenced by assertSsidIsValid(), and isValid().
isAddressStringValid()
bool signal_easel::ax25::Address::isAddressStringValid ()
References address_string_, signal_easel::ax25::K_MAXIMUM_ADDRESS_LENGTH, and signal_easel::ax25::K_MINIMUM_ADDRESS_LENGTH.
Referenced by isValid().
assertAddressStringIsValid()
void signal_easel::ax25::Address::assertAddressStringIsValid () private
References address_string_, signal_easel::Exception::AX25_INVALID_ADDRESS_LENGTH, signal_easel::Exception::AX25_INVALID_CHARACTER_IN_ADDRESS, signal_easel::ax25::K_MAXIMUM_ADDRESS_LENGTH, and signal_easel::ax25::K_MINIMUM_ADDRESS_LENGTH.
Referenced by assertIsValid(), decodeAddress(), and setAddressString().
assertSsidIsValid()
void signal_easel::ax25::Address::assertSsidIsValid () private
References signal_easel::Exception::AX25_INVALID_SSID, and isSsidValid().
Referenced by assertIsValid(), decodeAddress(), and setSsid().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Address & address) friend
Member Data Documentation
address_string_
std::string signal_easel::ax25::Address::address_string_ = "" private
Referenced by assertAddressStringIsValid(), decodeAddress(), encodeAddress(), getAddressString(), isAddressStringValid(), and setAddressString().
ssid_
uint8_t signal_easel::ax25::Address::ssid_ = 0x00 private
Referenced by decodeAddress(), encodeAddress(), getSsid(), isSsidValid(), and setSsid().
command_or_response_
bool signal_easel::ax25::Address::command_or_response_ = true private
Referenced by decodeAddress(), encodeAddress(), and isCommandOrResponse().
reserve_bit_1_
bool signal_easel::ax25::Address::reserve_bit_1_ = true private
Referenced by decodeAddress(), encodeAddress(), and isReservedBit1Set().
reserve_bit_2_
bool signal_easel::ax25::Address::reserve_bit_2_ = true private
Referenced by decodeAddress(), encodeAddress(), and isReservedBit2Set().
is_last_address_
bool signal_easel::ax25::Address::is_last_address_ = false private
Referenced by decodeAddress(), encodeAddress(), isLastAddress(), and setIsLastAddress().