SignalEasel: signal_easel::aprs::telemetry::AnalogParameter Class Reference
signal_easel::aprs::telemetry::AnalogParameter Class Reference
#include <telemetry_parameter.hpp>
Public Types
enum class Id : uint8_t {
A1 = 0 , A2 = 1 , A3 = 2 , A4 = 3 ,
A5 = 4 , B1 = 5 , B2 = 6 , B3 = 7 ,
B4 = 8 , B5 = 9 , B6 = 10 , B7 = 11 ,
B8 = 12
}
The ID of the telemetry parameter.
enum class Type : uint8_t { Analog = 0 , Digital = 1 }
The type of the telemetry parameter.
Public Member Functions
AnalogParameter (Id id)
An analog parameter.
double getCalculatedValue () const
Get the calculated value of the parameter using the formula y = ax^2 + bx + c.
std::string getCoefficientA () const
Get the A coefficient in the formula y = ax^2 + bx + c.
std::string getCoefficientB () const
Get the B coefficient in the formula y = ax^2 + bx + c.
std::string getCoefficientC () const
Get the C coefficient in the formula y = ax^2 + bx + c.
void getCoefficients (std::string &coefficient_a, std::string &coefficient_b, std::string &coefficient_c) const
Get all coefficients in the formula y = ax^2 + bx + c.
Id getId () const
Get the parameter ID.
std::string getLabel () const
Get the unit or label of the parameter.
std::string getName () const
Get the name of the parameter.
Type getType () const
Get the parameter type.
uint8_t getValue () const
Get the raw value of the parameter.
bool setCoefficientA (const std::string &coefficient)
Set the A coefficient in the formula y = ax^2 + bx + c.
bool setCoefficientB (const std::string &coefficient)
Set the B coefficient in the formula y = ax^2 + bx + c.
bool setCoefficientC (const std::string &coefficient)
Set the C coefficient in the formula y = ax^2 + bx + c.
bool setCoefficients (const std::string &coefficient_a, const std::string &coefficient_b, const std::string &coefficient_c)
Set all coefficients in the formula y = ax^2 + bx + c.
bool setName (const std::string &name)
Set the name of the parameter.
void setRawValue (uint8_t raw_value)
Set the raw value of the parameter. 0-255.
bool setUnitOrLabel (const std::string &unit_or_label)
Set the unit or label of the parameter.
Static Public Member Functions
static Type getType (Id id)
Get the type of the parameter.
Private Member Functions
bool validateParameterDescriptor (const std::string &descriptor)
Parameter names, along with units for analog parameters and labels for digital parameters, share the same constraints. This will validate these values dependent on their ID.
Private Attributes
double a_ {0.0}
The numerical value of the a coefficient.
double b_ {1.0}
The numerical value of the b coefficient.
double c_ {0.0}
The numerical value of the c coefficient.
std::string coefficient_a_ {"0"}
The a coefficient in the formula y = ax^2 + bx + c.
std::string coefficient_b_ {"1"}
The b coefficient in the formula y = ax^2 + bx + c.
std::string coefficient_c_ {"0"}
The c coefficient in the formula y = ax^2 + bx + c.
Id id_
std::string name_ {}
uint8_t raw_value_ {0}
The raw value of the analog parameter (0-255).
Type type_
std::string unit_or_label_ {}
Member Enumeration Documentation
Id
enum class signal_easel::aprs::telemetry::Parameter::Id : uint8_t strong inherited
The ID of the telemetry parameter.
Enumerator
A1
A2
A3
A4
A5
B1
B2
B3
B4
B5
B6
B7
B8
Type
enum class signal_easel::aprs::telemetry::Parameter::Type : uint8_t strong inherited
The type of the telemetry parameter.
Enumerator
Analog
Digital
Constructor & Destructor Documentation
AnalogParameter()
signal_easel::aprs::telemetry::AnalogParameter::AnalogParameter (Id id)
An analog parameter.
Parameters
id - The ID of the parameter, must be AX.
References signal_easel::aprs::telemetry::Parameter::Analog, signal_easel::Exception::APRS_TELEMETRY, and signal_easel::aprs::telemetry::Parameter::getType().
Member Function Documentation
setRawValue()
void signal_easel::aprs::telemetry::AnalogParameter::setRawValue (uint8_t raw_value) inline
Set the raw value of the parameter. 0-255.
Parameters
raw_value - The raw value of the parameter.
References raw_value_.
Referenced by TEST().
getValue()
uint8_t signal_easel::aprs::telemetry::AnalogParameter::getValue () const inline
Get the raw value of the parameter.
Returns
The raw value.
References raw_value_.
Referenced by TEST().
getCalculatedValue()
double signal_easel::aprs::telemetry::AnalogParameter::getCalculatedValue () const
Get the calculated value of the parameter using the formula y = ax^2 + bx + c.
Returns
The calculated value.
References a_, b_, c_, and raw_value_.
Referenced by TEST().
setCoefficientA()
bool signal_easel::aprs::telemetry::AnalogParameter::setCoefficientA (const std::string & coefficient)
Set the A coefficient in the formula y = ax^2 + bx + c.
Parameters
coefficient - The A coefficient.
Returns
true if the coefficient was set, false otherwise.
References a_, coefficient_a_, and signal_easel::aprs::telemetry::validateCoefficient().
Referenced by setCoefficients(), and TEST().
getCoefficientA()
std::string signal_easel::aprs::telemetry::AnalogParameter::getCoefficientA () const inline
Get the A coefficient in the formula y = ax^2 + bx + c.
Returns
The A coefficient.
References coefficient_a_.
Referenced by TEST().
setCoefficientB()
bool signal_easel::aprs::telemetry::AnalogParameter::setCoefficientB (const std::string & coefficient)
Set the B coefficient in the formula y = ax^2 + bx + c.
Parameters
coefficient - The B coefficient.
Returns
true if the coefficient was set, false otherwise.
References b_, coefficient_b_, and signal_easel::aprs::telemetry::validateCoefficient().
Referenced by setCoefficients().
getCoefficientB()
std::string signal_easel::aprs::telemetry::AnalogParameter::getCoefficientB () const inline
Get the B coefficient in the formula y = ax^2 + bx + c.
Returns
The B coefficient.
References coefficient_b_.
Referenced by TEST().
setCoefficientC()
bool signal_easel::aprs::telemetry::AnalogParameter::setCoefficientC (const std::string & coefficient)
Set the C coefficient in the formula y = ax^2 + bx + c.
Parameters
coefficient - The C coefficient.
Returns
true if the coefficient was set, false otherwise.
References c_, coefficient_c_, and signal_easel::aprs::telemetry::validateCoefficient().
Referenced by setCoefficients().
getCoefficientC()
std::string signal_easel::aprs::telemetry::AnalogParameter::getCoefficientC () const inline
Get the C coefficient in the formula y = ax^2 + bx + c.
Returns
The C coefficient.
References coefficient_c_.
Referenced by TEST().
setCoefficients()
bool signal_easel::aprs::telemetry::AnalogParameter::setCoefficients (const std::string & coefficient_a, const std::string & coefficient_b, const std::string & coefficient_c)
Set all coefficients in the formula y = ax^2 + bx + c.
Parameters
coefficient_a - The a coefficient.
coefficient_b - The b coefficient.
coefficient_c - The c coefficient.
Returns
true if all coefficients were set, false otherwise.
References setCoefficientA(), setCoefficientB(), and setCoefficientC().
Referenced by TEST().
getCoefficients()
void signal_easel::aprs::telemetry::AnalogParameter::getCoefficients (std::string & coefficient_a, std::string & coefficient_b, std::string & coefficient_c) const inline
Get all coefficients in the formula y = ax^2 + bx + c.
Parameters
[out] coefficient_a - The a coefficient.
[out] coefficient_b - The b coefficient.
[out] coefficient_c - The c coefficient.
References coefficient_a_, coefficient_b_, and coefficient_c_.
getType() [1/2]
static Type signal_easel::aprs::telemetry::Parameter::getType (Id id) inline static inherited
Get the type of the parameter.
Parameters
id - The ID of the parameter.
Returns
Type::Analog if the parameter is analog, Type::Digital if the parameter is digital.
References signal_easel::aprs::telemetry::Parameter::A1, signal_easel::aprs::telemetry::Parameter::A2, signal_easel::aprs::telemetry::Parameter::A3, signal_easel::aprs::telemetry::Parameter::A4, signal_easel::aprs::telemetry::Parameter::A5, signal_easel::aprs::telemetry::Parameter::Analog, signal_easel::Exception::APRS_TELEMETRY, signal_easel::aprs::telemetry::Parameter::B1, signal_easel::aprs::telemetry::Parameter::B2, signal_easel::aprs::telemetry::Parameter::B3, signal_easel::aprs::telemetry::Parameter::B4, signal_easel::aprs::telemetry::Parameter::B5, signal_easel::aprs::telemetry::Parameter::B6, signal_easel::aprs::telemetry::Parameter::B7, signal_easel::aprs::telemetry::Parameter::B8, and signal_easel::aprs::telemetry::Parameter::Digital.
Referenced by TEST().
getType() [2/2]
Type signal_easel::aprs::telemetry::Parameter::getType () const inline inherited
Get the parameter type.
Returns
Parameter type.
References signal_easel::aprs::telemetry::Parameter::type_.
Referenced by AnalogParameter(), signal_easel::aprs::telemetry::DigitalParameter::DigitalParameter(), signal_easel::aprs::telemetry::TelemetryData::getAnalog(), and signal_easel::aprs::telemetry::TelemetryData::getDigital().
getId()
Id signal_easel::aprs::telemetry::Parameter::getId () const inline inherited
Get the parameter ID.
Returns
Parameter ID.
References signal_easel::aprs::telemetry::Parameter::id_.
Referenced by TEST().
setName()
bool signal_easel::aprs::telemetry::Parameter::setName (const std::string & name) inherited
Set the name of the parameter.
Parameters
name - The name of the parameter.
Returns
true if the name was set (in bounds), false otherwise.
References signal_easel::aprs::telemetry::Parameter::name_, and signal_easel::aprs::telemetry::Parameter::validateParameterDescriptor().
Referenced by TEST().
getName()
std::string signal_easel::aprs::telemetry::Parameter::getName () const inline inherited
Get the name of the parameter.
Returns
The name of the parameter.
References signal_easel::aprs::telemetry::Parameter::name_.
Referenced by TEST().
setUnitOrLabel()
bool signal_easel::aprs::telemetry::Parameter::setUnitOrLabel (const std::string & unit_or_label) inherited
Set the unit or label of the parameter.
Parameters
unit_or_label - The unit or label of the parameter.
Returns
true if the unit or label was set (in bounds), false otherwise.
References signal_easel::aprs::telemetry::Parameter::unit_or_label_, and signal_easel::aprs::telemetry::Parameter::validateParameterDescriptor().
getLabel()
std::string signal_easel::aprs::telemetry::Parameter::getLabel () const inline inherited
Get the unit or label of the parameter.
Returns
The unit or label of the parameter.
References signal_easel::aprs::telemetry::Parameter::unit_or_label_.
validateParameterDescriptor()
bool signal_easel::aprs::telemetry::Parameter::validateParameterDescriptor (const std::string & descriptor) private inherited
Parameter names, along with units for analog parameters and labels for digital parameters, share the same constraints. This will validate these values dependent on their ID.
Parameters
descriptor - The name, unit, or label of the parameter.
Returns
true if the descriptor is valid, false otherwise.
References signal_easel::aprs::telemetry::Parameter::A1, signal_easel::aprs::telemetry::Parameter::A2, signal_easel::aprs::telemetry::Parameter::A3, signal_easel::aprs::telemetry::Parameter::A4, signal_easel::aprs::telemetry::Parameter::A5, signal_easel::aprs::telemetry::Parameter::B1, signal_easel::aprs::telemetry::Parameter::B2, signal_easel::aprs::telemetry::Parameter::B3, signal_easel::aprs::telemetry::Parameter::B4, signal_easel::aprs::telemetry::Parameter::B5, signal_easel::aprs::telemetry::Parameter::B6, signal_easel::aprs::telemetry::Parameter::B7, signal_easel::aprs::telemetry::Parameter::B8, and signal_easel::aprs::telemetry::Parameter::id_.
Referenced by signal_easel::aprs::telemetry::Parameter::setName(), and signal_easel::aprs::telemetry::Parameter::setUnitOrLabel().
Member Data Documentation
raw_value_
uint8_t signal_easel::aprs::telemetry::AnalogParameter::raw_value_ {0} private
The raw value of the analog parameter (0-255).
Referenced by getCalculatedValue(), getValue(), and setRawValue().
coefficient_a_
std::string signal_easel::aprs::telemetry::AnalogParameter::coefficient_a_ {"0"} private
The a coefficient in the formula y = ax^2 + bx + c.
Referenced by getCoefficientA(), getCoefficients(), and setCoefficientA().
coefficient_b_
std::string signal_easel::aprs::telemetry::AnalogParameter::coefficient_b_ {"1"} private
The b coefficient in the formula y = ax^2 + bx + c.
Referenced by getCoefficientB(), getCoefficients(), and setCoefficientB().
coefficient_c_
std::string signal_easel::aprs::telemetry::AnalogParameter::coefficient_c_ {"0"} private
The c coefficient in the formula y = ax^2 + bx + c.
Referenced by getCoefficientC(), getCoefficients(), and setCoefficientC().
a_
double signal_easel::aprs::telemetry::AnalogParameter::a_ {0.0} private
The numerical value of the a coefficient.
Referenced by getCalculatedValue(), and setCoefficientA().
b_
double signal_easel::aprs::telemetry::AnalogParameter::b_ {1.0} private
The numerical value of the b coefficient.
Referenced by getCalculatedValue(), and setCoefficientB().
c_
double signal_easel::aprs::telemetry::AnalogParameter::c_ {0.0} private
The numerical value of the c coefficient.
Referenced by getCalculatedValue(), and setCoefficientC().
id_
Id signal_easel::aprs::telemetry::Parameter::id_ private inherited
Referenced by signal_easel::aprs::telemetry::Parameter::Parameter(), signal_easel::aprs::telemetry::Parameter::getId(), and signal_easel::aprs::telemetry::Parameter::validateParameterDescriptor().
type_
Type signal_easel::aprs::telemetry::Parameter::type_ private inherited
Referenced by signal_easel::aprs::telemetry::Parameter::getType().
name_
std::string signal_easel::aprs::telemetry::Parameter::name_ {} private inherited
Referenced by signal_easel::aprs::telemetry::Parameter::Parameter(), signal_easel::aprs::telemetry::Parameter::getName(), and signal_easel::aprs::telemetry::Parameter::setName().
unit_or_label_
std::string signal_easel::aprs::telemetry::Parameter::unit_or_label_ {} private inherited
Referenced by signal_easel::aprs::telemetry::Parameter::Parameter(), signal_easel::aprs::telemetry::Parameter::getLabel(), and signal_easel::aprs::telemetry::Parameter::setUnitOrLabel().
The documentation for this class was generated from the following files:
telemetry_parameter.hpp
telemetry_parameter.cpp