Signal Easel: signal_easel::BitStream Class Reference
signal_easel::BitStream Class Reference
#include <bit_stream.hpp>
Public Member Functions
void addBits (const unsigned char *data, int num_bits)
void addOneBit ()
void addZeroBit ()
void dumpBitStream ()
void dumpBitStreamAsAscii ()
void dumpBitStreamAsHex ()
int getBitStreamLength () const
const std::vector< uint32_t > & getBitVector () const
int peakNextBit ()
Returns the next bit of the bit stream without removing it.
int peakNextByte ()
int8_t popNextBit ()
Returns the next bit of the bit stream that will be encoded.
void pushBufferToBitStream ()
After adding all of the data to the bit stream, this method will write the data left in the buffer.
Private Attributes
std::vector< uint32_t > bit_stream_ = std::vector<uint32_t>()
uint32_t bit_stream_buffer_ = 0
int bit_stream_index_ = 0
int bit_stream_length_ = 0
int bit_stream_offset_ = 0
Detailed Description
Bit stream is an array of 32 bit integers. The bits are stored in a 32 bit integer in the following way:
Characters: a a b b c c
varicode with 2x 0 bit padding added to the end of each character: '1011' '00' '1011' '00' '1011111' '00' '1011111' '00' '101111' '00' '101111' '00'
32 bit array: [0](10110010110010111110010111110010) {a, a, b, b, half of c } [1](11110010111100000000000000000000) {other half of c, 0 bits..}
Although this may not be the best way to store the bit stream, it makes it easier to understand.
Todo:
Add support for little endian and big endian.
Member Function Documentation
dumpBitStream()
void signal_easel::BitStream::dumpBitStream ()
References bit_stream_.
dumpBitStreamAsHex()
void signal_easel::BitStream::dumpBitStreamAsHex ()
References bit_stream_.
dumpBitStreamAsAscii()
void signal_easel::BitStream::dumpBitStreamAsAscii ()
References bit_stream_.
addBits()
void signal_easel::BitStream::addBits (const unsigned char * data, int num_bits)
References bit_stream_, bit_stream_buffer_, bit_stream_length_, and bit_stream_offset_.
Referenced by addOneBit(), addZeroBit(), and signal_easel::ax25::Frame::encodeFrame().
popNextBit()
int8_t signal_easel::BitStream::popNextBit ()
Returns the next bit of the bit stream that will be encoded.
Returns
int [1, 0, -1] -1 = no more bits in bit stream
References bit_stream_, bit_stream_index_, bit_stream_length_, and bit_stream_offset_.
Referenced by signal_easel::ax25::decodeNrzi(), signal_easel::ax25::deStuffBytes(), signal_easel::ax25::Frame::encodeFrame(), and signal_easel::ax25::findStartFlags().
peakNextBit()
int signal_easel::BitStream::peakNextBit ()
Returns the next bit of the bit stream without removing it.
Returns
int [1, 0, -1] -1 = no more bits in bit stream
References bit_stream_, bit_stream_index_, and bit_stream_offset_.
Referenced by signal_easel::ax25::deStuffBytes().
peakNextByte()
int signal_easel::BitStream::peakNextByte ()
References bit_stream_, bit_stream_index_, and bit_stream_offset_.
Referenced by signal_easel::ax25::findStartFlags().
pushBufferToBitStream()
void signal_easel::BitStream::pushBufferToBitStream ()
After adding all of the data to the bit stream, this method will write the data left in the buffer.
References bit_stream_, bit_stream_buffer_, bit_stream_index_, and bit_stream_offset_.
Referenced by signal_easel::ax25::decodeNrzi().
getBitStreamLength()
int signal_easel::BitStream::getBitStreamLength () const
References bit_stream_length_.
Referenced by signal_easel::ax25::decodeNrzi(), signal_easel::ax25::deStuffBytes(), signal_easel::ax25::Frame::encodeFrame(), and signal_easel::ax25::findStartFlags().
addOneBit()
void signal_easel::BitStream::addOneBit () inline
References addBits().
Referenced by signal_easel::ax25::decodeNrzi(), and signal_easel::ax25::Frame::encodeFrame().
addZeroBit()
void signal_easel::BitStream::addZeroBit () inline
References addBits().
Referenced by signal_easel::ax25::decodeNrzi(), and signal_easel::ax25::Frame::encodeFrame().
getBitVector()
const std::vector<uint32_t>& signal_easel::BitStream::getBitVector () const inline
References bit_stream_.
Referenced by signal_easel::ax25::findStartFlags().
Member Data Documentation
bit_stream_
std::vector<uint32_t> signal_easel::BitStream::bit_stream_ = std::vector<uint32_t>() private
Referenced by addBits(), dumpBitStream(), dumpBitStreamAsAscii(), dumpBitStreamAsHex(), getBitVector(), peakNextBit(), peakNextByte(), popNextBit(), and pushBufferToBitStream().
bit_stream_index_
int signal_easel::BitStream::bit_stream_index_ = 0 private
Referenced by peakNextBit(), peakNextByte(), popNextBit(), and pushBufferToBitStream().
bit_stream_buffer_
uint32_t signal_easel::BitStream::bit_stream_buffer_ = 0 private
Referenced by addBits(), and pushBufferToBitStream().
bit_stream_offset_
int signal_easel::BitStream::bit_stream_offset_ = 0 private
Referenced by addBits(), peakNextBit(), peakNextByte(), popNextBit(), and pushBufferToBitStream().
bit_stream_length_
int signal_easel::BitStream::bit_stream_length_ = 0 private
Referenced by addBits(), getBitStreamLength(), and popNextBit().