SignalEasel: signal_easel::aprs::telemetry::Parameter Class Reference
signal_easel::aprs::telemetry::Parameter Class Reference
A representation of APRS telemetry parameters.
#include <telemetry_parameter.hpp>
Public Types
enum class Id : uint8_t {
A1 = 0 , A2 = 1 , A3 = 2 , A4 = 3 ,
A5 = 4 , B1 = 5 , B2 = 6 , B3 = 7 ,
B4 = 8 , B5 = 9 , B6 = 10 , B7 = 11 ,
B8 = 12
}
The ID of the telemetry parameter.
enum class Type : uint8_t { Analog = 0 , Digital = 1 }
The type of the telemetry parameter.
Public Member Functions
Parameter (Id id, Type type)
Construct a new Parameter with the given ID.
virtual ~Parameter ()=default
Default destructor.
Id getId () const
Get the parameter ID.
std::string getLabel () const
Get the unit or label of the parameter.
std::string getName () const
Get the name of the parameter.
Type getType () const
Get the parameter type.
bool setName (const std::string &name)
Set the name of the parameter.
bool setUnitOrLabel (const std::string &unit_or_label)
Set the unit or label of the parameter.
Static Public Member Functions
static Type getType (Id id)
Get the type of the parameter.
Private Member Functions
bool validateParameterDescriptor (const std::string &descriptor)
Parameter names, along with units for analog parameters and labels for digital parameters, share the same constraints. This will validate these values dependent on their ID.
Private Attributes
Id id_
std::string name_ {}
Type type_
std::string unit_or_label_ {}
Detailed Description
A representation of APRS telemetry parameters.
Member Enumeration Documentation
Id
enum class signal_easel::aprs::telemetry::Parameter::Id : uint8_t strong
The ID of the telemetry parameter.
Enumerator
A1
A2
A3
A4
A5
B1
B2
B3
B4
B5
B6
B7
B8
Type
enum class signal_easel::aprs::telemetry::Parameter::Type : uint8_t strong
The type of the telemetry parameter.
Enumerator
Analog
Digital
Constructor & Destructor Documentation
Parameter()
signal_easel::aprs::telemetry::Parameter::Parameter (Id id, Type type)
Construct a new Parameter with the given ID.
Parameters
id - The ID of the parameter.
type - The type of the parameter.
References A1, id_, name_, and unit_or_label_.
~Parameter()
virtual signal_easel::aprs::telemetry::Parameter::~Parameter () virtual default
Default destructor.
Member Function Documentation
getType() [1/2]
static Type signal_easel::aprs::telemetry::Parameter::getType (Id id) inline static
Get the type of the parameter.
Parameters
id - The ID of the parameter.
Returns
Type::Analog if the parameter is analog, Type::Digital if the parameter is digital.
References A1, A2, A3, A4, A5, Analog, signal_easel::Exception::APRS_TELEMETRY, B1, B2, B3, B4, B5, B6, B7, B8, and Digital.
Referenced by TEST().
getId()
Id signal_easel::aprs::telemetry::Parameter::getId () const inline
Get the parameter ID.
Returns
Parameter ID.
References id_.
Referenced by TEST().
getType() [2/2]
Type signal_easel::aprs::telemetry::Parameter::getType () const inline
Get the parameter type.
Returns
Parameter type.
References type_.
Referenced by signal_easel::aprs::telemetry::AnalogParameter::AnalogParameter(), signal_easel::aprs::telemetry::DigitalParameter::DigitalParameter(), signal_easel::aprs::telemetry::TelemetryData::getAnalog(), and signal_easel::aprs::telemetry::TelemetryData::getDigital().
setName()
bool signal_easel::aprs::telemetry::Parameter::setName (const std::string & name)
Set the name of the parameter.
Parameters
name - The name of the parameter.
Returns
true if the name was set (in bounds), false otherwise.
References name_, and validateParameterDescriptor().
Referenced by TEST().
getName()
std::string signal_easel::aprs::telemetry::Parameter::getName () const inline
Get the name of the parameter.
Returns
The name of the parameter.
References name_.
Referenced by TEST().
setUnitOrLabel()
bool signal_easel::aprs::telemetry::Parameter::setUnitOrLabel (const std::string & unit_or_label)
Set the unit or label of the parameter.
Parameters
unit_or_label - The unit or label of the parameter.
Returns
true if the unit or label was set (in bounds), false otherwise.
References unit_or_label_, and validateParameterDescriptor().
getLabel()
std::string signal_easel::aprs::telemetry::Parameter::getLabel () const inline
Get the unit or label of the parameter.
Returns
The unit or label of the parameter.
References unit_or_label_.
validateParameterDescriptor()
bool signal_easel::aprs::telemetry::Parameter::validateParameterDescriptor (const std::string & descriptor) private
Parameter names, along with units for analog parameters and labels for digital parameters, share the same constraints. This will validate these values dependent on their ID.
Parameters
descriptor - The name, unit, or label of the parameter.
Returns
true if the descriptor is valid, false otherwise.
References A1, A2, A3, A4, A5, B1, B2, B3, B4, B5, B6, B7, B8, and id_.
Referenced by setName(), and setUnitOrLabel().
Member Data Documentation
id_
Id signal_easel::aprs::telemetry::Parameter::id_ private
Referenced by Parameter(), getId(), and validateParameterDescriptor().
type_
Type signal_easel::aprs::telemetry::Parameter::type_ private
Referenced by getType().
name_
std::string signal_easel::aprs::telemetry::Parameter::name_ {} private
Referenced by Parameter(), getName(), and setName().
unit_or_label_
std::string signal_easel::aprs::telemetry::Parameter::unit_or_label_ {} private
Referenced by Parameter(), getLabel(), and setUnitOrLabel().
The documentation for this class was generated from the following files:
telemetry_parameter.hpp
telemetry_parameter.cpp