Signal Easel: signal_easel::DataModulator Class Reference
signal_easel::DataModulator Class Reference abstract
Another abstract base class for modulators that turn text/binary data into audio.
#include <modulator.hpp>
Public Member Functions
DataModulator (const Settings &settings=Settings())
virtual ~DataModulator ()=default
void addBytes (const std::vector< uint8_t > &data)
Add data to the audio buffer.
void addString (const std::string &data)
Add string data to the audio buffer.
void clearBuffer ()
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
void writeToFile (const std::string &filename)
Write the audio to a file.
void writeToPulseAudio ()
Write the audio to the default PulseAudio output device.
Protected Member Functions
void addAudioSample (int16_t sample)
Add a PCM sample to the audio buffer.
void addSilence (uint32_t duration_in_samples)
Add silence to the audio buffer.
void addSineWave (uint16_t frequency, uint16_t num_samples)
Add a sine wave to the audio buffer.
virtual void encodeBytes (const std::vector< uint8_t > &data)=0
This is overridden by the child classes to encode the data that is passed in by addBytes and addString.
Protected Attributes
std::vector< int16_t > audio_buffer_ = {}
Settings settings_
Private Member Functions
void addMorseCode (const std::string &input_string)
Add morse code to the output audio.
Private Attributes
double sine_wave_phase_ = 0.0
Used with addSineWave to keep a continuous phase between calls.
Detailed Description
Another abstract base class for modulators that turn text/binary data into audio.
Constructor & Destructor Documentation
DataModulator()
signal_easel::DataModulator::DataModulator (const Settings & settings = Settings()) inline
~DataModulator()
virtual signal_easel::DataModulator::~DataModulator () virtual default
Member Function Documentation
addBytes()
void signal_easel::DataModulator::addBytes (const std::vector< uint8_t > & data)
Add data to the audio buffer.
Parameters
data The data to add
References encodeBytes().
addString()
void signal_easel::DataModulator::addString (const std::string & data)
Add string data to the audio buffer.
Parameters
data The string to add
References encodeBytes().
Referenced by main(), and TEST().
encodeBytes()
virtual void signal_easel::DataModulator::encodeBytes (const std::vector< uint8_t > & data) protected pure virtual
This is overridden by the child classes to encode the data that is passed in by addBytes and addString.
Parameters
data The data to encode and add to the audio buffer
Implemented in signal_easel::afsk::Modulator.
Referenced by addBytes(), and addString().
clearBuffer()
void signal_easel::Modulator::clearBuffer () inherited
Clears the audio buffer. Adds the call sign if it's in the before or before_and_after modes.
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Settings::NONE, signal_easel::Modulator::settings_, and signal_easel::Modulator::sine_wave_phase_.
Referenced by signal_easel::Modulator::Modulator().
writeToFile()
void signal_easel::Modulator::writeToFile (const std::string & filename) inherited
Write the audio to a file.
Parameters
filename The name/path of the file to write to
Exceptions
MWAVException Throws an exception if the file cannot be opened or if there is no data to write
References signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::addSilence(), signal_easel::Settings::AFTER, signal_easel::Modulator::audio_buffer_, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::Settings::BEFORE_AND_AFTER, signal_easel::Settings::call_sign, signal_easel::Settings::call_sign_mode, signal_easel::Settings::call_sign_pause_seconds, signal_easel::Exception::FILE_OPEN_ERROR, signal_easel::Exception::INVALID_CALL_SIGN, signal_easel::isCallSignValid(), signal_easel::Exception::NO_DATA_TO_WRITE, signal_easel::Settings::NONE, and signal_easel::Modulator::settings_.
Referenced by TEST().
writeToPulseAudio()
void signal_easel::Modulator::writeToPulseAudio () inherited
Write the audio to the default PulseAudio output device.
References signal_easel::Modulator::audio_buffer_, signal_easel::PULSE_AUDIO_APP_NAME, signal_easel::Exception::PULSE_AUDIO_DISABLED, signal_easel::PULSE_AUDIO_SAMPLE_SPEC, signal_easel::Exception::PULSE_DRAIN_ERROR, signal_easel::Exception::PULSE_OPEN_ERROR, and signal_easel::Exception::PULSE_WRITE_ERROR.
Referenced by main().
addAudioSample()
void signal_easel::Modulator::addAudioSample (int16_t sample) inline protected inherited
Add a PCM sample to the audio buffer.
Parameters
sample The PCM sample to add
References signal_easel::Modulator::audio_buffer_.
Referenced by signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), and signal_easel::afsk::Modulator::encodeBytes().
addSilence()
void signal_easel::Modulator::addSilence (uint32_t duration_in_samples) inline protected inherited
Add silence to the audio buffer.
Parameters
duration_in_samples
References signal_easel::Modulator::addAudioSample().
Referenced by signal_easel::Modulator::addMorseCode(), signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
addSineWave()
void signal_easel::Modulator::addSineWave (uint16_t frequency, uint16_t num_samples) protected inherited
Add a sine wave to the audio buffer.
Parameters
frequency The frequency of the sine wave in Hz
num_samples The number of samples to add
References signal_easel::Modulator::addAudioSample(), signal_easel::Settings::amplitude, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::MAX_SAMPLE_VALUE, signal_easel::Modulator::settings_, signal_easel::Modulator::sine_wave_phase_, and signal_easel::TWO_PI_VAL.
Referenced by signal_easel::Modulator::addMorseCode().
addMorseCode()
void signal_easel::Modulator::addMorseCode (const std::string & input_string) private inherited
Add morse code to the output audio.
Parameters
input_string the string to convert to morse code
References signal_easel::Modulator::addSilence(), signal_easel::Modulator::addSineWave(), signal_easel::DASH_LENGTH, signal_easel::DOT_LENGTH, signal_easel::Exception::EMPTY_INPUT_STRING, signal_easel::Exception::INVALID_MORSE_CHAR, signal_easel::LETTER_SPACE_LENGTH, signal_easel::MORSE_CODE_MAP, signal_easel::MORSE_TONE_FREQUENCY, and signal_easel::TIME_BETWEEN_SYMBOLS.
Referenced by signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
Member Data Documentation
settings_
Settings signal_easel::Modulator::settings_ protected inherited
Referenced by signal_easel::Modulator::addSineWave(), signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
audio_buffer_
std::vector<int16_t> signal_easel::Modulator::audio_buffer_ = {} protected inherited
Referenced by signal_easel::Modulator::addAudioSample(), signal_easel::Modulator::clearBuffer(), signal_easel::Modulator::writeToFile(), and signal_easel::Modulator::writeToPulseAudio().
sine_wave_phase_
double signal_easel::Modulator::sine_wave_phase_ = 0.0 private inherited
Used with addSineWave to keep a continuous phase between calls.
Referenced by signal_easel::Modulator::addSineWave(), and signal_easel::Modulator::clearBuffer().