SignalEasel: signal_easel::aprs::Demodulator Class Reference
signal_easel::aprs::Demodulator Class Reference
#include <aprs.hpp>
Public Types
enum class AsciiResult { SUCCESS , NO_SYN , NO_EOT }
Public Member Functions
Demodulator (afsk::Settings settings=afsk::Settings())
void clearBuffer ()
Clears the audio buffer.
aprs::Packet::Type getType ()
void loadAudioFromFile (const std::string &file_name)
Open a WAV file and load it's contents into the audio buffer.
bool lookForAx25Packet ()
AsciiResult lookForString (std::string &output)
bool parseExperimentalPacket (aprs::ExperimentalPacket &experimental)
bool parseMessagePacket (aprs::MessagePacket &message)
If the packet was a message packet, this function will try to parse the packet into a message packet.
bool parsePositionPacket (aprs::PositionPacket &position)
If the packet was a position packet, this function will try to parse the packet into it's positional data.
bool parseTelemetryPacket (aprs::TelemetryPacket &packet)
If the packet was a telemetry packet, this function will try to parse the packet and populate the telemetry data object.
void printFrame ()
ProcessResults processAudioBuffer ()
Protected Member Functions
const std::vector< int16_t > & getAudioBuffer () const
Protected Attributes
std::vector< int16_t > audio_buffer_ = {}
BitStream output_bit_stream_ {}
Settings settings_
Private Member Functions
void audioBufferToBaseBandSignal (ProcessResults &results)
Takes the raw signal and converts it into the FSK baseband signal.
void baseBandToBitStream (ProcessResults &results)
Takes the base band signal and converts it into a bit stream if the signal is valid.
void populateGenericFields (aprs::Packet &packet) const
Private Attributes
afsk::Settings afsk_settings_
std::vector< uint8_t > base_band_signal_ {}
ax25::Frame frame_ {}
aprs::Packet::Type type_ = aprs::Packet::Type::UNKNOWN
Friends
class Receiver
Member Enumeration Documentation
AsciiResult
enum class signal_easel::afsk::Demodulator::AsciiResult strong inherited
Enumerator
SUCCESS
NO_SYN
NO_EOT
Constructor & Destructor Documentation
Demodulator()
signal_easel::aprs::Demodulator::Demodulator (afsk::Settings settings = afsk::Settings()) inline
Member Function Documentation
lookForAx25Packet()
bool signal_easel::aprs::Demodulator::lookForAx25Packet ()
References signal_easel::aprs::Packet::EXPERIMENTAL, frame_, signal_easel::ax25::Frame::getInformation(), signal_easel::aprs::Packet::MESSAGE, signal_easel::afsk::Demodulator::output_bit_stream_, signal_easel::ax25::Frame::parseBitStream(), signal_easel::aprs::Packet::POSITION, signal_easel::aprs::Packet::TELEMETRY_BIT_SENSE_PROJ_NAME, signal_easel::aprs::Packet::TELEMETRY_COEFFICIENT, signal_easel::aprs::Packet::TELEMETRY_DATA_REPORT, signal_easel::aprs::Packet::TELEMETRY_PARAMETER_NAME, signal_easel::aprs::Packet::TELEMETRY_PARAMETER_UNIT, type_, and signal_easel::aprs::Packet::UNKNOWN.
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
getType()
aprs::Packet::Type signal_easel::aprs::Demodulator::getType () inline
References type_.
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
parseMessagePacket()
bool signal_easel::aprs::Demodulator::parseMessagePacket (aprs::MessagePacket & message)
If the packet was a message packet, this function will try to parse the packet into a message packet.
Parameters
message (out) The message packet
Returns
true if the packet was a valid message packet
References signal_easel::aprs::MessagePacket::addressee, frame_, signal_easel::ax25::Frame::getInformation(), signal_easel::aprs::Packet::MESSAGE, signal_easel::aprs::MessagePacket::message, signal_easel::aprs::MessagePacket::message_id, populateGenericFields(), and type_.
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
parsePositionPacket()
bool signal_easel::aprs::Demodulator::parsePositionPacket (aprs::PositionPacket & position)
If the packet was a position packet, this function will try to parse the packet into it's positional data.
Todo:
This function will not be friendly to many types of aprs position packets.
Parameters
position (out) The position packet
Returns
true if the packet was fully parsed
false if the packet was not a valid position packet
References signal_easel::aprs::PositionPacket::altitude, signal_easel::aprs::base91Decode(), signal_easel::aprs::PositionPacket::comment, signal_easel::aprs::PositionPacket::course, frame_, signal_easel::ax25::Frame::getInformation(), signal_easel::aprs::PositionPacket::latitude, signal_easel::aprs::PositionPacket::longitude, populateGenericFields(), signal_easel::aprs::Packet::POSITION, signal_easel::aprs::Packet::PRIMARY, signal_easel::aprs::Packet::SECONDARY, signal_easel::aprs::PositionPacket::speed, signal_easel::aprs::Packet::symbol, signal_easel::aprs::Packet::symbol_table, signal_easel::aprs::PositionPacket::time_code, and type_.
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
parseExperimentalPacket()
bool signal_easel::aprs::Demodulator::parseExperimentalPacket (aprs::ExperimentalPacket & experimental)
Todo:
assert here or something instead. Same with other parse functions
References signal_easel::aprs::ExperimentalPacket::data, signal_easel::aprs::Packet::EXPERIMENTAL, frame_, signal_easel::ax25::Frame::getInformation(), signal_easel::aprs::ExperimentalPacket::packet_type_char, populateGenericFields(), and type_.
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
parseTelemetryPacket()
bool signal_easel::aprs::Demodulator::parseTelemetryPacket (aprs::TelemetryPacket & packet)
If the packet was a telemetry packet, this function will try to parse the packet and populate the telemetry data object.
Parameters
packet - The telemetry packet to populate
Returns
true if the packet was successfully parsed, false otherwise.
Todo:
assert here or something instead. Same with other parse functions
References signal_easel::aprs::telemetry::TelemetryTranscoder::decodeMessage(), frame_, signal_easel::ax25::Frame::getInformationRef(), populateGenericFields(), signal_easel::aprs::Packet::TELEMETRY_BIT_SENSE_PROJ_NAME, signal_easel::aprs::Packet::TELEMETRY_COEFFICIENT, signal_easel::aprs::TelemetryPacket::telemetry_data, signal_easel::aprs::Packet::TELEMETRY_DATA_REPORT, signal_easel::aprs::Packet::TELEMETRY_PARAMETER_NAME, signal_easel::aprs::Packet::TELEMETRY_PARAMETER_UNIT, signal_easel::aprs::TelemetryPacket::telemetry_type, and type_.
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
printFrame()
void signal_easel::aprs::Demodulator::printFrame ()
References frame_.
Referenced by TEST().
populateGenericFields()
void signal_easel::aprs::Demodulator::populateGenericFields (aprs::Packet & packet) const private
References signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, frame_, signal_easel::ax25::Frame::getDestinationAddress(), signal_easel::ax25::Frame::getSourceAddress(), signal_easel::aprs::Packet::source_address, and signal_easel::aprs::Packet::source_ssid.
Referenced by parseExperimentalPacket(), parseMessagePacket(), parsePositionPacket(), and parseTelemetryPacket().
processAudioBuffer()
afsk::Demodulator::ProcessResults signal_easel::afsk::Demodulator::processAudioBuffer () inherited
References signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal(), and signal_easel::afsk::Demodulator::baseBandToBitStream().
Referenced by signal_easel::aprs::Receiver::decode(), and TEST().
lookForString()
afsk::Demodulator::AsciiResult signal_easel::afsk::Demodulator::lookForString (std::string & output) inherited
References signal_easel::afsk::Demodulator::NO_EOT, signal_easel::afsk::Demodulator::NO_SYN, and signal_easel::afsk::Demodulator::SUCCESS.
Referenced by TEST().
audioBufferToBaseBandSignal()
void signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal (ProcessResults & results) private inherited
Takes the raw signal and converts it into the FSK baseband signal.
Todo:
This needs to be cleaned up.
Parameters
results (out) results The results of the processing.
References signal_easel::afsk::AFSK_BP_FILTER_ORDER, signal_easel::afsk::AFSK_BP_INCLUDED_BANDWIDTH, signal_easel::afsk::AFSK_BP_MARK_LOWER_CUTOFF, signal_easel::afsk::AFSK_BP_MARK_UPPER_CUTOFF, signal_easel::afsk::AFSK_BP_SPACE_LOWER_CUTOFF, signal_easel::afsk::AFSK_BP_SPACE_UPPER_CUTOFF, signal_easel::afsk::AFSK_MARK_FREQUENCY, signal_easel::afsk::AFSK_MINIMUM_SNR, signal_easel::afsk::AFSK_SPACE_FREQUENCY, signal_easel::AUDIO_SAMPLE_RATE, signal_easel::AUDIO_SAMPLE_RATE_D, signal_easel::bandPassFilter(), signal_easel::MAX_SAMPLE_VALUE, signal_easel::Exception::NON_MATCHING_FILTER_VECTORS, signal_easel::afsk::Demodulator::ProcessResults::rms, signal_easel::afsk::Demodulator::ProcessResults::snr, and signal_easel::TWO_PI_VAL.
Referenced by signal_easel::afsk::Demodulator::processAudioBuffer().
baseBandToBitStream()
void signal_easel::afsk::Demodulator::baseBandToBitStream (ProcessResults & results) private inherited
Takes the base band signal and converts it into a bit stream if the signal is valid.
Parameters
results (out) results The results of the processing.
The sample clock counts up to 40 and then resets.
Symbols are 40 samples long. This clock is used to determine when to add a bit to the bit stream.
Used to detect the actual symbol boundary.
Todo:
some form of 'confidence rating' could be helpful here
References signal_easel::afsk::AFSK_SAMPLES_PER_SYMBOL.
Referenced by signal_easel::afsk::Demodulator::processAudioBuffer().
clearBuffer()
void signal_easel::Demodulator::clearBuffer () inline inherited
Clears the audio buffer.
References signal_easel::Demodulator::audio_buffer_.
loadAudioFromFile()
void signal_easel::Demodulator::loadAudioFromFile (const std::string & file_name) inherited
Open a WAV file and load it's contents into the audio buffer.
Parameters
file_name The name/path of the file to open
References signal_easel::Demodulator::audio_buffer_, and signal_easel::Exception::FILE_OPEN_ERROR.
Referenced by TEST().
getAudioBuffer()
const std::vector< int16_t > & signal_easel::Demodulator::getAudioBuffer () const inline protected inherited
References signal_easel::Demodulator::audio_buffer_.
Friends And Related Function Documentation
Receiver
friend class Receiver friend
Member Data Documentation
frame_
ax25::Frame signal_easel::aprs::Demodulator::frame_ {} private
Referenced by signal_easel::aprs::Receiver::decode(), lookForAx25Packet(), parseExperimentalPacket(), parseMessagePacket(), parsePositionPacket(), parseTelemetryPacket(), populateGenericFields(), and printFrame().
type_
aprs::Packet::Type signal_easel::aprs::Demodulator::type_ = aprs::Packet::Type::UNKNOWN private
Referenced by getType(), lookForAx25Packet(), parseExperimentalPacket(), parseMessagePacket(), parsePositionPacket(), and parseTelemetryPacket().
output_bit_stream_
BitStream signal_easel::afsk::Demodulator::output_bit_stream_ {} protected inherited
Referenced by signal_easel::aprs::Receiver::decode(), and lookForAx25Packet().
base_band_signal_
std::vector<uint8_t> signal_easel::afsk::Demodulator::base_band_signal_ {} private inherited
afsk_settings_
afsk::Settings signal_easel::afsk::Demodulator::afsk_settings_ private inherited
settings_
Settings signal_easel::Demodulator::settings_ protected inherited
audio_buffer_
std::vector<int16_t> signal_easel::Demodulator::audio_buffer_ = {} protected inherited
Referenced by signal_easel::Demodulator::clearBuffer(), signal_easel::Demodulator::getAudioBuffer(), and signal_easel::Demodulator::loadAudioFromFile().
The documentation for this class was generated from the following files:
aprs.hpp
aprs_demodulator.cpp