Signal Easel: signal_easel::aprs::Receiver Class Reference
signal_easel::aprs::Receiver Class Reference
#include <aprs.hpp>
Classes
struct Stats
Public Member Functions
Receiver (aprs::Settings settings=aprs::Settings())
bool getAprsExperimental (aprs::Experimental &experimental_packet, ax25::Frame &frame)
bool getAprsMessage (aprs::MessagePacket &message_packet, ax25::Frame &frame)
bool getAprsPosition (aprs::PositionPacket &position_packet, ax25::Frame &frame)
uint64_t getLatency () const
bool getOtherAprsPacket (ax25::Frame &frame)
double getSNR ()
Stats getStats ()
double getVolume () const
bool process () override
Returns true if there was enough data to process.
Protected Member Functions
bool detectSignal (const PulseAudioBuffer &audio_buffer)
Protected Attributes
afsk::Settings afsk_settings_
afsk::Demodulator demodulator_
PulseAudioReader pulse_audio_reader_ {}
std::vector< int16_t > receive_buffer_ {}
Settings settings_
Private Member Functions
void decode () override
Private Attributes
Demodulator aprs_demodulator_ {}
std::vector< std::pair< ax25::Frame, aprs::Experimental > > aprs_experimental_ {}
std::vector< std::pair< ax25::Frame, aprs::MessagePacket > > aprs_messages_ {}
std::vector< std::pair< ax25::Frame, aprs::PositionPacket > > aprs_positions_ {}
afsk::Demodulator::ProcessResults demodulation_res_ {}
std::vector< ax25::Frame > other_aprs_packets_ {}
Stats stats_ {}
Class Documentation
signal_easel::aprs::Receiver::Stats
struct signal_easel::aprs::Receiver::Stats
Class Members
uint32_t total_message_packets
uint32_t num_message_packets_failed
uint32_t total_position_packets
uint32_t num_position_packets_failed
uint32_t total_experimental_packets
uint32_t num_experimental_packets_failed
uint32_t total_other_packets
uint32_t current_message_packets_in_queue
uint32_t current_position_packets_in_queue
uint32_t current_experimental_packets_in_queue
uint32_t current_other_packets_in_queue
Constructor & Destructor Documentation
Receiver()
signal_easel::aprs::Receiver::Receiver (aprs::Settings settings = aprs::Settings()) inline
Member Function Documentation
getAprsMessage()
bool signal_easel::aprs::Receiver::getAprsMessage (aprs::MessagePacket & message_packet, ax25::Frame & frame)
References aprs_messages_.
getAprsPosition()
bool signal_easel::aprs::Receiver::getAprsPosition (aprs::PositionPacket & position_packet, ax25::Frame & frame)
References aprs_positions_.
getAprsExperimental()
bool signal_easel::aprs::Receiver::getAprsExperimental (aprs::Experimental & experimental_packet, ax25::Frame & frame)
References aprs_experimental_.
getOtherAprsPacket()
bool signal_easel::aprs::Receiver::getOtherAprsPacket (ax25::Frame & frame)
References other_aprs_packets_.
getSNR()
double signal_easel::aprs::Receiver::getSNR () inline
References demodulation_res_, and signal_easel::afsk::Demodulator::ProcessResults::snr.
getStats()
Stats signal_easel::aprs::Receiver::getStats () inline
References stats_.
decode()
void signal_easel::aprs::Receiver::decode () override private virtual
Reimplemented from signal_easel::afsk::Receiver.
References aprs_demodulator_, aprs_experimental_, aprs_messages_, aprs_positions_, signal_easel::Exception::APRS_RECEIVER_BUFFER_FULL, signal_easel::aprs::Receiver::Stats::current_experimental_packets_in_queue, signal_easel::aprs::Receiver::Stats::current_message_packets_in_queue, signal_easel::aprs::Receiver::Stats::current_other_packets_in_queue, signal_easel::aprs::Receiver::Stats::current_position_packets_in_queue, signal_easel::aprs::PositionPacket::decoded_timestamp, demodulation_res_, signal_easel::afsk::Receiver::demodulator_, signal_easel::aprs::Packet::EXPERIMENTAL, signal_easel::aprs::Demodulator::frame_, signal_easel::aprs::Demodulator::getType(), signal_easel::aprs::Demodulator::lookForAx25Packet(), signal_easel::aprs::Packet::MESSAGE, signal_easel::aprs::Receiver::Stats::num_experimental_packets_failed, signal_easel::aprs::Receiver::Stats::num_message_packets_failed, signal_easel::aprs::Receiver::Stats::num_position_packets_failed, other_aprs_packets_, signal_easel::afsk::Demodulator::output_bit_stream_, signal_easel::aprs::Demodulator::parseExperimentalPacket(), signal_easel::aprs::Demodulator::parseMessagePacket(), signal_easel::aprs::Demodulator::parsePositionPacket(), signal_easel::aprs::Packet::POSITION, signal_easel::afsk::Demodulator::processAudioBuffer(), stats_, signal_easel::aprs::Receiver::Stats::total_experimental_packets, signal_easel::aprs::Receiver::Stats::total_message_packets, signal_easel::aprs::Receiver::Stats::total_other_packets, and signal_easel::aprs::Receiver::Stats::total_position_packets.
process()
bool signal_easel::afsk::Receiver::process () override virtual inherited
Returns true if there was enough data to process.
Returns
true
false
Implements signal_easel::Receiver.
References signal_easel::afsk::Receiver::detectSignal(), signal_easel::PulseAudioReader::getAudioBuffer(), signal_easel::PulseAudioReader::process(), and signal_easel::Receiver::pulse_audio_reader_.
Referenced by main().
detectSignal()
bool signal_easel::afsk::Receiver::detectSignal (const PulseAudioBuffer & audio_buffer) protected inherited
References signal_easel::afsk::AFSK_RECEIVED_MIN_SAMPLES, and signal_easel::afsk::AFSK_SNR_THRESHOLD.
Referenced by signal_easel::afsk::Receiver::process().
getLatency()
uint64_t signal_easel::Receiver::getLatency () const inline inherited
References signal_easel::PulseAudioReader::getLatency(), and signal_easel::Receiver::pulse_audio_reader_.
getVolume()
double signal_easel::Receiver::getVolume () const inline inherited
References signal_easel::PulseAudioReader::getVolume(), and signal_easel::Receiver::pulse_audio_reader_.
Member Data Documentation
aprs_messages_
std::vector<std::pair<ax25::Frame, aprs::MessagePacket> > signal_easel::aprs::Receiver::aprs_messages_ {} private
Referenced by decode(), and getAprsMessage().
aprs_positions_
std::vector<std::pair<ax25::Frame, aprs::PositionPacket> > signal_easel::aprs::Receiver::aprs_positions_ {} private
Referenced by decode(), and getAprsPosition().
aprs_experimental_
std::vector<std::pair<ax25::Frame, aprs::Experimental> > signal_easel::aprs::Receiver::aprs_experimental_ {} private
Referenced by decode(), and getAprsExperimental().
other_aprs_packets_
std::vector<ax25::Frame> signal_easel::aprs::Receiver::other_aprs_packets_ {} private
Referenced by decode(), and getOtherAprsPacket().
stats_
Stats signal_easel::aprs::Receiver::stats_ {} private
Referenced by decode(), and getStats().
demodulation_res_
afsk::Demodulator::ProcessResults signal_easel::aprs::Receiver::demodulation_res_ {} private
Referenced by decode(), and getSNR().
aprs_demodulator_
Demodulator signal_easel::aprs::Receiver::aprs_demodulator_ {} private
Referenced by decode().
demodulator_
afsk::Demodulator signal_easel::afsk::Receiver::demodulator_ protected inherited
Referenced by decode().
afsk_settings_
afsk::Settings signal_easel::afsk::Receiver::afsk_settings_ protected inherited
receive_buffer_
std::vector<int16_t> signal_easel::afsk::Receiver::receive_buffer_ {} protected inherited
pulse_audio_reader_
PulseAudioReader signal_easel::Receiver::pulse_audio_reader_ {} protected inherited
Referenced by signal_easel::Receiver::getLatency(), signal_easel::Receiver::getVolume(), and signal_easel::afsk::Receiver::process().
settings_
Settings signal_easel::Receiver::settings_ protected inherited