SignalEasel: commandline-demo.cpp File Reference
commandline-demo.cpp File Reference
#include "mwav.h"
#include <iostream>
#include <string>
#include <stdexcept>
Macros
#define OUTPUT_FILE "output.wav"
Functions
int getIntInput ()
std::string getStringInput ()
int main ()
Macro Definition Documentation
OUTPUT_FILE
#define OUTPUT_FILE "output.wav"
OUT OF DATE, NEEDS TO BE UPDATED
Function Documentation
getIntInput()
int getIntInput ()
Referenced by main().
getStringInput()
std::string getStringInput ()
Referenced by main().
main()
int main ()
References getIntInput(), getStringInput(), and OUTPUT_FILE.