Signal Easel: signal_easel Namespace Reference
signal_easel Namespace Reference
Namespaces
afsk
Audio Frequency Shift Keying (AFSK)
aprs
ax25
Classes
class BitStream
class DataModulator
Another abstract base class for modulators that turn text/binary data into audio.
class Demodulator
The base class for all demodulators that turn audio into data.
class Exception
class Modulator
The abstract base class for all modulators that turn data into audio.
struct MorseChar
class PulseAudioReader
class Receiver
struct Settings
The universal settings for MWAV.
Typedefs
typedef std::array< int16_t, PULSE_AUDIO_BUFFER_SIZE > PulseAudioBuffer
Functions
bool addLocationData (const aprs::PositionPacket &packet, const aprs::Packet &required_fields, std::vector< uint8_t > &info)
void AddRequiredFields (const aprs::Packet &required_fields, ax25::Frame &frame)
std::vector< double > bandPassFilter (const std::vector< double > &input, double sample_rate, double lower_cutoff, double upper_cutoff, size_t filter_order=4)
A band-pass filter implementation.
std::vector< uint8_t > base91Encode (int value, unsigned int num_bytes)
bool checkLocationData (const aprs::PositionPacket &location)
bool CheckPacketData (const aprs::Packet &packet)
std::vector< double > computeDenCoeffs (unsigned int filter_order, double low_cutoff, double upper_cutoff)
std::vector< double > computeHP (unsigned int filter_order)
std::vector< double > computeLP (unsigned int filter_order)
std::vector< double > computeNumCoeffs (unsigned int filter_order, double lower_cutoff, double upper_cutoff, const std::vector< double > &den_c)
int8_t convertToBipolar (bool bit)
Converts a bit to it's bipolar value (0 = 1, 1 = -1)
std::vector< uint8_t > encodePacket (const aprs::Packet &required_fields, std::vector< uint8_t > &info)
std::vector< double > filter (const std::vector< double > &input_vec, const std::vector< double > &coeff_b, const std::vector< double > &coeff_a)
int8_t getBpBitAtIndex (const std::vector< uint8_t > &bytes, size_t bit_index)
Gets the bipolar value of a bit at a given index from a vector of bytes.
bool isBitSet (uint8_t byte, uint8_t bit_position)
For reading a byte MSB first.
bool isCallSignValid (const std::string &call_sign)
Basic checks to see if a call sign is valid.
std::vector< double > trinomialMultiply (unsigned int filter_order, const std::vector< double > &b_coeffs, const std::vector< double > &c_coeffs)
Variables
constexpr uint32_t AUDIO_SAMPLE_RATE = 48000
The sample rate of the audio.
constexpr double AUDIO_SAMPLE_RATE_D
Just a double version of AUDIO_SAMPLE_RATE. I'm tired of casting.
constexpr size_t BUFFER_SIZE_IN_SECONDS = 1
constexpr uint16_t DASH_LENGTH = DOT_LENGTH * 3
constexpr uint16_t DOT_LENGTH = 0.06 * AUDIO_SAMPLE_RATE
The length of a morse dot in seconds. 0.06 is the minimum for 20wpm.
constexpr uint16_t LETTER_SPACE_LENGTH = DOT_LENGTH * 3
constexpr uint32_t MAX_AUDIO_BUFFER_SIZE = AUDIO_SAMPLE_RATE * 60 * 5
The maximum size of the audio buffer (5 minutes)
constexpr uint32_t MAX_SAMPLE_VALUE = 32767
The maximum value of a sample (2^15 - 1)
static const std::array< std::string, 36 > MORSE_CODE_MAP
constexpr uint16_t MORSE_TONE_FREQUENCY = 1000
constexpr uint8_t NUM_PULSE_CHANNELS = 1
constexpr double PI_VAL = 3.14159265358979323846
Constant for PI used throughout the project.
const std::string PULSE_AUDIO_APP_NAME = "SignalEasel"
constexpr size_t PULSE_AUDIO_BUFFER_SIZE = 200
constexpr pa_sample_format_t PULSE_AUDIO_SAMPLE_FORMAT = PA_SAMPLE_S16NE
constexpr pa_sample_spec PULSE_AUDIO_SAMPLE_SPEC
constexpr uint32_t SAMPLE_RESOLUTION = 16
The number of bits per sample (16-bit PCM)
constexpr uint16_t TIME_BETWEEN_SYMBOLS = DOT_LENGTH
constexpr double TWO_PI_VAL = 2.0 * PI_VAL
Constant for 2*PI used throughout the project.
Class Documentation
signal_easel::MorseChar
struct signal_easel::MorseChar
Class Members
int val
const char * morse
Typedef Documentation
PulseAudioBuffer
typedef std::array<int16_t, PULSE_AUDIO_BUFFER_SIZE> signal_easel::PulseAudioBuffer
Function Documentation
convertToBipolar()
int8_t signal_easel::convertToBipolar (bool bit) inline
Converts a bit to it's bipolar value (0 = 1, 1 = -1)
Parameters
bit The bit to convert
Returns
int8_t The bipolar value of the bit (-1 or 1)
Referenced by getBpBitAtIndex().
isBitSet()
bool signal_easel::isBitSet (uint8_t byte, uint8_t bit_position) inline
For reading a byte MSB first.
Parameters
byte The input byte
bit_position The index of the bit to read (0 - 7, MSB - LSB)
Returns
true The bit is set
false The bit is not set
Referenced by signal_easel::afsk::Modulator::convertToNRZI(), and getBpBitAtIndex().
getBpBitAtIndex()
int8_t signal_easel::getBpBitAtIndex (const std::vector< uint8_t > & bytes, size_t bit_index) inline
Gets the bipolar value of a bit at a given index from a vector of bytes.
Parameters
bytes The vector of bytes
bit_index
Returns
int8_t
References convertToBipolar(), and isBitSet().
Referenced by signal_easel::afsk::Modulator::encodeBytes().
base91Encode()
std::vector<uint8_t> signal_easel::base91Encode (int value, unsigned int num_bytes)
References signal_easel::Exception::BASE_91_ENCODE_VALUE_NOT_CORRECT_SIZE.
Referenced by addLocationData().
CheckPacketData()
bool signal_easel::CheckPacketData (const aprs::Packet & packet)
References signal_easel::Exception::APRS_INVALID_DESTINATION_ADDRESS_LENGTH, signal_easel::Exception::APRS_INVALID_DESTINATION_SSID, signal_easel::Exception::APRS_INVALID_SOURCE_ADDRESS_LENGTH, signal_easel::Exception::APRS_INVALID_SOURCE_SSID, signal_easel::Exception::APRS_INVALID_SYMBOL, signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, and signal_easel::aprs::Packet::symbol.
Referenced by AddRequiredFields().
checkLocationData()
bool signal_easel::checkLocationData (const aprs::PositionPacket & location)
References signal_easel::aprs::PositionPacket::altitude, signal_easel::Exception::APRS_LOCATION_INVALID_TIME_CODE_LENGTH, signal_easel::aprs::PositionPacket::course, signal_easel::aprs::PositionPacket::latitude, signal_easel::aprs::PositionPacket::longitude, signal_easel::aprs::PositionPacket::speed, and signal_easel::aprs::PositionPacket::time_code.
Referenced by addLocationData().
AddRequiredFields()
void signal_easel::AddRequiredFields (const aprs::Packet & required_fields, ax25::Frame & frame)
References CheckPacketData(), signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::ax25::Frame::setDestinationAddress(), signal_easel::ax25::Frame::setSourceAddress(), signal_easel::aprs::Packet::source_address, and signal_easel::aprs::Packet::source_ssid.
Referenced by encodePacket().
encodePacket()
std::vector<uint8_t> signal_easel::encodePacket (const aprs::Packet & required_fields, std::vector< uint8_t > & info)
References AddRequiredFields(), signal_easel::ax25::Frame::encodeFrame(), and signal_easel::ax25::Frame::setInformation().
Referenced by signal_easel::aprs::Modulator::encodeMessagePacket(), and signal_easel::aprs::Modulator::encodePositionPacket().
addLocationData()
bool signal_easel::addLocationData (const aprs::PositionPacket & packet, const aprs::Packet & required_fields, std::vector< uint8_t > & info)
Todo:
generate an invalid frame
References signal_easel::aprs::PositionPacket::altitude, signal_easel::Exception::APRS_INVALID_LOCATION_DATA, base91Encode(), checkLocationData(), signal_easel::aprs::PositionPacket::comment, signal_easel::aprs::PositionPacket::course, signal_easel::aprs::PositionPacket::latitude, signal_easel::aprs::PositionPacket::longitude, signal_easel::aprs::Packet::PRIMARY, signal_easel::aprs::PositionPacket::speed, signal_easel::aprs::Packet::symbol, signal_easel::aprs::Packet::symbol_table, and signal_easel::aprs::PositionPacket::time_code.
Referenced by signal_easel::aprs::Modulator::encodePositionPacket().
trinomialMultiply()
std::vector<double> signal_easel::trinomialMultiply (unsigned int filter_order, const std::vector< double > & b_coeffs, const std::vector< double > & c_coeffs)
Referenced by computeDenCoeffs().
computeLP()
std::vector<double> signal_easel::computeLP (unsigned int filter_order)
Referenced by computeHP().
computeHP()
std::vector<double> signal_easel::computeHP (unsigned int filter_order)
References computeLP().
Referenced by computeNumCoeffs().
computeDenCoeffs()
std::vector<double> signal_easel::computeDenCoeffs (unsigned int filter_order, double low_cutoff, double upper_cutoff)
References PI, and trinomialMultiply().
Referenced by bandPassFilter().
computeNumCoeffs()
std::vector<double> signal_easel::computeNumCoeffs (unsigned int filter_order, double lower_cutoff, double upper_cutoff, const std::vector< double > & den_c)
References computeHP(), and PI.
Referenced by bandPassFilter().
filter()
std::vector<double> signal_easel::filter (const std::vector< double > & input_vec, const std::vector< double > & coeff_b, const std::vector< double > & coeff_a)
Referenced by bandPassFilter().
bandPassFilter()
std::vector< double > signal_easel::bandPassFilter (const std::vector< double > & input, double sample_rate, double lower_cutoff, double upper_cutoff, size_t filter_order = 4)
A band-pass filter implementation.
Parameters
input The input signal
sample_rate The sample rate of the input signal (ie. 44100)
lower_cutoff The lower cutoff frequency
upper_cutoff The upper cutoff frequency
filter_order The order of the filter (ie. 4)
Returns
std::vector<double> The filtered signal
References computeDenCoeffs(), computeNumCoeffs(), and filter().
Referenced by signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal().
isCallSignValid()
bool signal_easel::isCallSignValid (const std::string & call_sign)
Basic checks to see if a call sign is valid.
Parameters
call_sign The call sign to check
Returns
true if the call sign is valid, false otherwise
Referenced by signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
Variable Documentation
MORSE_TONE_FREQUENCY
constexpr uint16_t signal_easel::MORSE_TONE_FREQUENCY = 1000 inline constexpr
Referenced by signal_easel::Modulator::addMorseCode().
DOT_LENGTH
constexpr uint16_t signal_easel::DOT_LENGTH = 0.06 * AUDIO_SAMPLE_RATE inline constexpr
The length of a morse dot in seconds. 0.06 is the minimum for 20wpm.
97-119: (b) The call sign must be transmitted with an emission authorized for the transmitting channel in one of the following ways: (1) By a CW emission. When keyed by an automatic device used only for identification, the speed must not exceed 20 words per minute.
Referenced by signal_easel::Modulator::addMorseCode().
DASH_LENGTH
constexpr uint16_t signal_easel::DASH_LENGTH = DOT_LENGTH * 3 inline constexpr
Referenced by signal_easel::Modulator::addMorseCode().
LETTER_SPACE_LENGTH
constexpr uint16_t signal_easel::LETTER_SPACE_LENGTH = DOT_LENGTH * 3 inline constexpr
Referenced by signal_easel::Modulator::addMorseCode().
TIME_BETWEEN_SYMBOLS
constexpr uint16_t signal_easel::TIME_BETWEEN_SYMBOLS = DOT_LENGTH inline constexpr
Referenced by signal_easel::Modulator::addMorseCode().
MORSE_CODE_MAP
const std::array<std::string, 36> signal_easel::MORSE_CODE_MAP static
Referenced by signal_easel::Modulator::addMorseCode().
AUDIO_SAMPLE_RATE
constexpr uint32_t signal_easel::AUDIO_SAMPLE_RATE = 48000 inline constexpr
The sample rate of the audio.
This value was chosen as it's cleanly devisable by 1200 and 60, this is helpful for AFSK and SSTV. Choosing the standard 44100 creates problems, especially with SSTV which was created in the days of 60Hz.
Referenced by signal_easel::Modulator::addSineWave(), signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal(), signal_easel::Modulator::clearBuffer(), and signal_easel::Modulator::writeToFile().
AUDIO_SAMPLE_RATE_D
constexpr double signal_easel::AUDIO_SAMPLE_RATE_D inline constexpr
Initial value:
=
    static_cast<double>(AUDIO_SAMPLE_RATE)
Just a double version of AUDIO_SAMPLE_RATE. I'm tired of casting.
Referenced by signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal().
SAMPLE_RESOLUTION
constexpr uint32_t signal_easel::SAMPLE_RESOLUTION = 16 inline constexpr
The number of bits per sample (16-bit PCM)
MAX_SAMPLE_VALUE
constexpr uint32_t signal_easel::MAX_SAMPLE_VALUE = 32767 inline constexpr
The maximum value of a sample (2^15 - 1)
Referenced by signal_easel::Modulator::addSineWave(), signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal(), and signal_easel::afsk::Modulator::encodeBytes().
MAX_AUDIO_BUFFER_SIZE
constexpr uint32_t signal_easel::MAX_AUDIO_BUFFER_SIZE = AUDIO_SAMPLE_RATE * 60 * 5 inline constexpr
The maximum size of the audio buffer (5 minutes)
PI_VAL
constexpr double signal_easel::PI_VAL = 3.14159265358979323846 inline constexpr
Constant for PI used throughout the project.
TWO_PI_VAL
constexpr double signal_easel::TWO_PI_VAL = 2.0 * PI_VAL inline constexpr
Constant for 2*PI used throughout the project.
Referenced by signal_easel::Modulator::addSineWave(), signal_easel::afsk::Demodulator::audioBufferToBaseBandSignal(), and signal_easel::afsk::Modulator::encodeBytes().
PULSE_AUDIO_SAMPLE_FORMAT
constexpr pa_sample_format_t signal_easel::PULSE_AUDIO_SAMPLE_FORMAT = PA_SAMPLE_S16NE inline constexpr
NUM_PULSE_CHANNELS
constexpr uint8_t signal_easel::NUM_PULSE_CHANNELS = 1 inline constexpr
PULSE_AUDIO_SAMPLE_SPEC
constexpr pa_sample_spec signal_easel::PULSE_AUDIO_SAMPLE_SPEC inline constexpr
Initial value:
= {
    PULSE_AUDIO_SAMPLE_FORMAT, AUDIO_SAMPLE_RATE, NUM_PULSE_CHANNELS}
Referenced by signal_easel::Modulator::writeToPulseAudio().
PULSE_AUDIO_APP_NAME
const std::string signal_easel::PULSE_AUDIO_APP_NAME = "SignalEasel"
Referenced by signal_easel::Modulator::writeToPulseAudio().
BUFFER_SIZE_IN_SECONDS
constexpr size_t signal_easel::BUFFER_SIZE_IN_SECONDS = 1 inline constexpr
PULSE_AUDIO_BUFFER_SIZE
constexpr size_t signal_easel::PULSE_AUDIO_BUFFER_SIZE = 200 inline constexpr