Signal Easel: signal_easel::aprs Namespace Reference
signal_easel::aprs Namespace Reference
Classes
class Demodulator
struct Experimental
This packet type will have two { characters at the start.
struct MessageAck
struct MessagePacket
class Modulator
struct Packet
struct PositionPacket
class Receiver
struct Settings
struct Telemetry
Enumerations
enum class TelemetryPacketType {
DATA_REPORT , PARAM_NAME , PARAM_UNIT , PARAM_COEF ,
BIT_SENSE_PROJ_NAME
}
Functions
void addAnalogValue (uint8_t value, std::vector< uint8_t > &info)
bool addLocationData (const aprs::PositionPacket &packet, const aprs::Packet &required_fields, std::vector< uint8_t > &info)
void AddRequiredFields (const aprs::Packet &required_fields, ax25::Frame &frame)
void addUnitOrParam (const std::string &unit_or_param, std::vector< uint8_t > &info, size_t max_length, bool first=false)
int base91Decode (std::vector< uint8_t > encoded)
std::vector< uint8_t > base91Encode (int value, unsigned int num_bytes)
bool checkLocationData (const aprs::PositionPacket &location)
bool CheckPacketData (const aprs::Packet &packet)
std::vector< uint8_t > encodePacket (const aprs::Packet &required_fields, std::vector< uint8_t > &info)
Enumeration Type Documentation
TelemetryPacketType
enum signal_easel::aprs::TelemetryPacketType strong
Enumerator
DATA_REPORT
PARAM_NAME
PARAM_UNIT
PARAM_COEF
BIT_SENSE_PROJ_NAME
Function Documentation
addAnalogValue()
void signal_easel::aprs::addAnalogValue (uint8_t value, std::vector< uint8_t > & info)
Referenced by signal_easel::aprs::Telemetry::encode().
addUnitOrParam()
void signal_easel::aprs::addUnitOrParam (const std::string & unit_or_param, std::vector< uint8_t > & info, size_t max_length, bool first = false)
Referenced by signal_easel::aprs::Telemetry::encode().
base91Encode()
std::vector< uint8_t > signal_easel::aprs::base91Encode (int value, unsigned int num_bytes)
References signal_easel::Exception::BASE_91_ENCODE_VALUE_NOT_CORRECT_SIZE.
Referenced by addLocationData().
base91Decode()
int signal_easel::aprs::base91Decode (std::vector< uint8_t > encoded)
Referenced by signal_easel::aprs::Demodulator::parsePositionPacket().
CheckPacketData()
bool signal_easel::aprs::CheckPacketData (const aprs::Packet & packet)
References signal_easel::Exception::APRS_INVALID_DESTINATION_ADDRESS_LENGTH, signal_easel::Exception::APRS_INVALID_DESTINATION_SSID, signal_easel::Exception::APRS_INVALID_SOURCE_ADDRESS_LENGTH, signal_easel::Exception::APRS_INVALID_SOURCE_SSID, signal_easel::Exception::APRS_INVALID_SYMBOL, signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::aprs::Packet::source_address, signal_easel::aprs::Packet::source_ssid, and signal_easel::aprs::Packet::symbol.
Referenced by AddRequiredFields().
checkLocationData()
bool signal_easel::aprs::checkLocationData (const aprs::PositionPacket & location)
References signal_easel::aprs::PositionPacket::altitude, signal_easel::Exception::APRS_LOCATION_INVALID_TIME_CODE_LENGTH, signal_easel::aprs::PositionPacket::course, signal_easel::aprs::PositionPacket::latitude, signal_easel::aprs::PositionPacket::longitude, signal_easel::aprs::PositionPacket::speed, and signal_easel::aprs::PositionPacket::time_code.
Referenced by addLocationData().
AddRequiredFields()
void signal_easel::aprs::AddRequiredFields (const aprs::Packet & required_fields, ax25::Frame & frame)
References CheckPacketData(), signal_easel::aprs::Packet::destination_address, signal_easel::aprs::Packet::destination_ssid, signal_easel::ax25::Frame::setDestinationAddress(), signal_easel::ax25::Frame::setSourceAddress(), signal_easel::aprs::Packet::source_address, and signal_easel::aprs::Packet::source_ssid.
Referenced by encodePacket().
encodePacket()
std::vector< uint8_t > signal_easel::aprs::encodePacket (const aprs::Packet & required_fields, std::vector< uint8_t > & info)
References AddRequiredFields(), signal_easel::ax25::Frame::encodeFrame(), and signal_easel::ax25::Frame::setInformation().
Referenced by signal_easel::aprs::Modulator::encodeMessageAck(), signal_easel::aprs::Modulator::encodeMessagePacket(), and signal_easel::aprs::Modulator::encodePositionPacket().
addLocationData()
bool signal_easel::aprs::addLocationData (const aprs::PositionPacket & packet, const aprs::Packet & required_fields, std::vector< uint8_t > & info)
Todo:
generate an invalid frame
Todo:
Bearing and Number/Range/Quality
References signal_easel::aprs::PositionPacket::altitude, signal_easel::Exception::APRS_INVALID_LOCATION_DATA, base91Encode(), checkLocationData(), signal_easel::aprs::PositionPacket::comment, signal_easel::aprs::PositionPacket::course, signal_easel::aprs::PositionPacket::latitude, signal_easel::aprs::PositionPacket::longitude, signal_easel::aprs::Packet::PRIMARY, signal_easel::aprs::PositionPacket::speed, signal_easel::aprs::Packet::symbol, signal_easel::aprs::Packet::symbol_table, and signal_easel::aprs::PositionPacket::time_code.
Referenced by signal_easel::aprs::Modulator::encodePositionPacket().