Signal Easel: signal_easel::ax25 Namespace Reference
signal_easel::ax25 Namespace Reference
Classes
class Address
AX.25 Address class. For encoding and decoding AX.25 addresses.
class Frame
Functions
uint16_t calculateFcs (const std::vector< uint8_t > &input_data)
Calculate the Frame Check Sequence (FCS) on a vector of bytes.
BitStream decodeNrzi (BitStream &bit_stream)
Convert a bit stream from NRZI to standard encoding.
std::vector< uint8_t > deStuffBytes (BitStream &bit_stream)
int findStartFlags (BitStream &bit_stream)
Finds the start flags in the bit stream and removes them.
std::ostream & operator<< (std::ostream &os, const Address &frame)
std::ostream & operator<< (std::ostream &os, const Frame &frame)
void print_hex (uint8_t byte)
uint8_t reverse_bits (uint8_t byte)
uint8_t reverseByte (uint8_t byte)
Reverse a byte.
Variables
const uint8_t AX25_FLAG = 0x7E
constexpr size_t K_ADDRESS_CHARS_LENGTH = 6
constexpr uint8_t K_FLAG = 0x7E
constexpr size_t K_MAX_INFORMATION_LENGTH = 256
constexpr size_t K_MAX_REPEATER_ADDRESSES = 2
constexpr size_t K_MAX_SSID_VALUE = 15
constexpr size_t K_MAXIMUM_ADDRESS_LENGTH = 6
constexpr size_t K_MINIMUM_ADDRESS_LENGTH = 3
constexpr uint8_t K_PID = 0xF0
constexpr size_t K_POSTAMBLE_LENGTH = 33
constexpr size_t K_PREAMBLE_LENGTH = 33
Function Documentation
operator<<() [1/2]
std::ostream & signal_easel::ax25::operator<< (std::ostream & os, const Address & frame)
reverse_bits()
uint8_t signal_easel::ax25::reverse_bits (uint8_t byte)
Referenced by deStuffBytes().
print_hex()
void signal_easel::ax25::print_hex (uint8_t byte)
decodeNrzi()
BitStream signal_easel::ax25::decodeNrzi (BitStream & bit_stream)
Convert a bit stream from NRZI to standard encoding.
Parameters
bit_stream The bit stream to decode (NRZI encoded)
Returns
BitStream The decoded bit stream
References signal_easel::BitStream::addOneBit(), signal_easel::BitStream::addZeroBit(), signal_easel::BitStream::getBitStreamLength(), signal_easel::BitStream::popNextBit(), and signal_easel::BitStream::pushBufferToBitStream().
Referenced by signal_easel::ax25::Frame::parseBitStream().
findStartFlags()
int signal_easel::ax25::findStartFlags (BitStream & bit_stream)
Finds the start flags in the bit stream and removes them.
Parameters
bit_stream The bit stream to search
Returns
int -1 if no flags were found, otherwise the number of opening flags
References AX25_FLAG, signal_easel::BitStream::getBitStreamLength(), signal_easel::BitStream::getBitVector(), signal_easel::BitStream::peakNextByte(), and signal_easel::BitStream::popNextBit().
Referenced by signal_easel::ax25::Frame::parseBitStream().
deStuffBytes()
std::vector<uint8_t> signal_easel::ax25::deStuffBytes (BitStream & bit_stream)
References signal_easel::BitStream::getBitStreamLength(), signal_easel::BitStream::peakNextBit(), signal_easel::BitStream::popNextBit(), and reverse_bits().
Referenced by signal_easel::ax25::Frame::parseBitStream().
calculateFcs()
uint16_t signal_easel::ax25::calculateFcs (const std::vector< uint8_t > & input_data)
Calculate the Frame Check Sequence (FCS) on a vector of bytes.
From: https://gist.github.com/andresv/4611897
Parameters
input_data The data to calculate the FCS on
Returns
uint16_t The calculated FCS
Referenced by signal_easel::ax25::Frame::buildFrame(), and TEST().
reverseByte()
uint8_t signal_easel::ax25::reverseByte (uint8_t byte)
Reverse a byte.
Parameters
byte The byte to reverse
Returns
uint8_t The reversed byte
Referenced by signal_easel::ax25::Frame::addToBuildBuffer().
operator<<() [2/2]
std::ostream& signal_easel::ax25::operator<< (std::ostream & os, const Frame & frame)
Variable Documentation
AX25_FLAG
const uint8_t signal_easel::ax25::AX25_FLAG = 0x7E
Referenced by findStartFlags().
K_MINIMUM_ADDRESS_LENGTH
constexpr size_t signal_easel::ax25::K_MINIMUM_ADDRESS_LENGTH = 3 inline constexpr
Referenced by signal_easel::ax25::Address::assertAddressStringIsValid(), and signal_easel::ax25::Address::isAddressStringValid().
K_MAXIMUM_ADDRESS_LENGTH
constexpr size_t signal_easel::ax25::K_MAXIMUM_ADDRESS_LENGTH = 6 inline constexpr
Referenced by signal_easel::ax25::Address::assertAddressStringIsValid(), and signal_easel::ax25::Address::isAddressStringValid().
K_MAX_SSID_VALUE
constexpr size_t signal_easel::ax25::K_MAX_SSID_VALUE = 15 inline constexpr
Referenced by signal_easel::ax25::Address::isSsidValid().
K_ADDRESS_CHARS_LENGTH
constexpr size_t signal_easel::ax25::K_ADDRESS_CHARS_LENGTH = 6 inline constexpr
Referenced by signal_easel::ax25::Address::decodeAddress(), and signal_easel::ax25::Address::encodeAddress().
K_MAX_REPEATER_ADDRESSES
constexpr size_t signal_easel::ax25::K_MAX_REPEATER_ADDRESSES = 2 inline constexpr
Referenced by signal_easel::ax25::Frame::addRepeaterAddress(), and signal_easel::ax25::Frame::isFrameValid().
K_MAX_INFORMATION_LENGTH
constexpr size_t signal_easel::ax25::K_MAX_INFORMATION_LENGTH = 256 inline constexpr
Referenced by signal_easel::ax25::Frame::isFrameValid(), and signal_easel::ax25::Frame::setInformation().
K_FLAG
constexpr uint8_t signal_easel::ax25::K_FLAG = 0x7E inline constexpr
Referenced by signal_easel::ax25::Frame::encodeFrame().
K_PID
constexpr uint8_t signal_easel::ax25::K_PID = 0xF0 inline constexpr
K_PREAMBLE_LENGTH
constexpr size_t signal_easel::ax25::K_PREAMBLE_LENGTH = 33 inline constexpr
Referenced by signal_easel::ax25::Frame::encodeFrame().
K_POSTAMBLE_LENGTH
constexpr size_t signal_easel::ax25::K_POSTAMBLE_LENGTH = 33 inline constexpr
Referenced by signal_easel::ax25::Frame::encodeFrame().