SignalEasel: signal_easel::aprs::telemetry Namespace Reference
signal_easel::aprs::telemetry Namespace Reference
Classes
class AnalogParameter
class DigitalParameter
A digital parameter.
class Parameter
A representation of APRS telemetry parameters.
class TelemetryData
A container for telemetry data. Contains all of the components of APRS telemetry messages.
class TelemetryTranscoder
A class for encoding and decoding APRS telemetry messages.
Functions
bool validateCoefficient (const std::string &coefficient)
Wrapper for validateCoefficient that does not require the numerical value.
bool validateCoefficient (const std::string &coefficient, double &numerical_value)
Validate the format of a coefficient.
Variables
constexpr size_t TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH = 11
The length of the telemetry message address section (non-data report). Example: ":N0CALL-1 :".
Detailed Description
=*============================= SignalEasel ==============================*= A C++ library for audio modulation/demodulation into analog & digital modes. Detailed documentation can be found here: https://signaleasel.joshuajer.red
Author
Joshua Jerred
Date
2024-08-17
Copyright
Copyright 2024 Joshua Jerred. All rights reserved.
License: This project is licensed under the GNU GPL v3.0 license.
=*========================================================================*=
Function Documentation
validateCoefficient() [1/2]
bool signal_easel::aprs::telemetry::validateCoefficient (const std::string & coefficient, double & numerical_value)
Validate the format of a coefficient.
Parameters
coefficient - The coefficient to validate.
[out] numerical_value - The numerical value of the coefficient. This is only set if the coefficient is valid.
Returns
true if the coefficient is valid, false otherwise.
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterCoefficientMessage(), signal_easel::aprs::telemetry::AnalogParameter::setCoefficientA(), signal_easel::aprs::telemetry::AnalogParameter::setCoefficientB(), signal_easel::aprs::telemetry::AnalogParameter::setCoefficientC(), and validateCoefficient().
validateCoefficient() [2/2]
bool signal_easel::aprs::telemetry::validateCoefficient (const std::string & coefficient)
Wrapper for validateCoefficient that does not require the numerical value.
Parameters
coefficient - The coefficient to validate.
Returns
true if the coefficient is valid, false otherwise.
References validateCoefficient().
Variable Documentation
TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH
constexpr size_t signal_easel::aprs::telemetry::TELEMETRY_MESSAGE_ADDRESS_SECTION_LENGTH = 11 inline constexpr
The length of the telemetry message address section (non-data report). Example: ":N0CALL-1 :".
Referenced by signal_easel::aprs::telemetry::TelemetryTranscoder::decodeBitSenseMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::decodeMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterCoefficientMessage(), signal_easel::aprs::telemetry::TelemetryTranscoder::decodeParameterDescriptor(), and signal_easel::aprs::telemetry::TelemetryTranscoder::decodeValidateHeader().