SignalEasel: pulse_test.cpp File Reference
pulse_test.cpp File Reference
PulseAudio output test. Does not use gtest.
#include <SignalEasel/afsk.hpp>
#include <SignalEasel/aprs.hpp>
#include <SignalEasel/pulse_audio.hpp>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <unistd.h>
Macros
#define PULSE_AUDIO_ENABLED
Functions
int main ()
void printVolumeBar (double volume, uint16_t latency)
Detailed Description
PulseAudio output test. Does not use gtest.
=*========SignalEasel========*= A friendly library for signal modulation and demodulation. https://github.com/joshua-jerred/Giraffe https://joshuajer.red/signal-easel =*===========================*=
Date
2023-12-09
=*=======================*=
Copyright
2023 Joshua Jerred
License: GNU GPLv3
Macro Definition Documentation
PULSE_AUDIO_ENABLED
#define PULSE_AUDIO_ENABLED
Function Documentation
printVolumeBar()
void printVolumeBar (double volume, uint16_t latency)
main()
int main ()
References signal_easel::DataModulator::addString(), signal_easel::afsk::Receiver::process(), and signal_easel::Modulator::writeToPulseAudio().