Signal Easel: signal_easel::sstv::Modulator::YCbCr Struct Reference
signal_easel::sstv::Modulator::YCbCr Struct Reference
Public Member Functions
YCbCr ()
YCbCr (const SstvImage::Pixel &pixel)
YCbCr (double r, double g, double b)
void CalculateYCbCr (double r, double g, double b)
Public Attributes
double cb = 0
double cr = 0
double y = 0
Constructor & Destructor Documentation
YCbCr() [1/3]
signal_easel::sstv::Modulator::YCbCr::YCbCr () inline
YCbCr() [2/3]
signal_easel::sstv::Modulator::YCbCr::YCbCr (double r, double g, double b) inline
References CalculateYCbCr().
YCbCr() [3/3]
signal_easel::sstv::Modulator::YCbCr::YCbCr (const SstvImage::Pixel & pixel) inline
References CalculateYCbCr().
Member Function Documentation
CalculateYCbCr()
void signal_easel::sstv::Modulator::YCbCr::CalculateYCbCr (double r, double g, double b) inline
References cb, cr, signal_easel::Exception::SSTV_INVALID_RGB_VALUE, and y.
Referenced by YCbCr().
Member Data Documentation
y
double signal_easel::sstv::Modulator::YCbCr::y = 0
Referenced by CalculateYCbCr(), and signal_easel::sstv::Modulator::readImageLine().
cb
double signal_easel::sstv::Modulator::YCbCr::cb = 0
Referenced by CalculateYCbCr(), and signal_easel::sstv::Modulator::readImageLine().
cr
double signal_easel::sstv::Modulator::YCbCr::cr = 0
Referenced by CalculateYCbCr(), and signal_easel::sstv::Modulator::readImageLine().