FROM debian:stable-slim

# joshuajerred/signaleasel
# To run the image: docker run -it --rm --name signaleasel joshuajerred/signaleasel

# Install dependencies
RUN apt-get update && apt-get install -y \
   git \
   build-essential \
   cmake \
   libpulse-dev
