name: SignalEasel Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install GTest
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Install Pulse Audio Dev Packages
      run: sudo apt-get install libpulse-dev
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DMWAV_UNIT_TESTS=ON ..
    - name: Build the SignalEasel library
      run: |
        cd build
        make SignalEasel -j 4
    - name: Build Tests
      run: |
        cd build
        make signal_easel_unit_tests
    - name: Run Tests
      run: |
        cd build/tests
        ./signal_easel_unit_tests