name: MWAV Tests (C++ CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joshuajerred/giraffe:latest
      options: --user root
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: CMake Configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build the MWAV library
      run: |
        cd build
        make MWavLib

  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: joshuajerred/giraffe:latest
      options: --user root
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: CMake Configure
      run: |
        mkdir build
        cd build
        cmake -DMWAV_UNIT_TESTS=ON ..
    - name: Build Tests
      run: |
        cd build
        make mwav_unit_tests
    - name: Run Tests
      run: |
        cd build/tests
        ./mwav_unit_tests